### ISSUE TITLE
Habits and Tasks have disappeared!

### ISSUE THREAD

**Issue by JellyBean22** [HabitRPG/habitica#1133]
I just joined some guilds (and created one) then when I went back to the front page all but three of my habits and tasks have disappeared! Please help as I had lots of both dailies and tasks and can't survive without them!!!

Tried both beta & pod and it's the same.

Chrome 27 
Win 7

**Comment by lefnire** [comment]
What's your user id

**Comment by lefnire** [comment]
you may want to leave the guilds for the time being, looks like you're experiencing https://github.com/codeparty/racer/issues/57 - which should have been fixed on my end, but i may have to do a second pass

**Comment by JellyBean22** [comment]
My user id is 57a68581-bdfa-4cb7-8651-1e86a2af69a4
I have left all guilds apart from the one I created and my habits and tasks are still gone.

**Comment by lefnire** [comment]
hmm.. i'm showing all your tasks in the database just fine, it's definitely
a result of that mentioned bug. Are you in a party as well?

**Comment by JellyBean22** [comment]
No am not in any party.
Weird.... I logged in again after clearing cache and everything and it's still the same.

**Comment by JellyBean22** [comment]
I just checked the page source and my habits and tasks are all there but still not actually displaying on the page.

**Comment by lefnire** [comment]
Oh! any active tags?

**Comment by JellyBean22** [comment]
Lol I'm an idiot!, I didn't spot I had one tag on!

**Comment by lefnire** [comment]
heart attack central! ;)

**Comment by JellyBean22** [comment]
Thanks for looking into it.
Keep up the fantastic work! :)

**Comment by lefnire** [comment]
thanks :)
