### ISSUE TITLE
Orb of Rebirth does not always reset stats immediately (client-side issue probably)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#12892]
As reported by @hyunyeol (81025674-937a-43ca-9d3d-cb61c34e76ff), the Orb of Rebirth did not immediately reset their stats, resulting in them using it twice:

"I purchased the Orb of Rebirth after reaching level 100 (after checking that it costed 0 gem).
(Fortunately before the purchase, I kept a screenshot to keep some of the # of streaks. The attachment shows that I had 61 gems & reached the level 100.)
On my first click of the purchase of the Orb, it did not reset my level or class, and the Orb was still remaining for 0 gem at the store. So I purchased it again, and this time things had reset.
However, I noticed that it somehow charged me 6 gems
Everything else besides the gems seems as it should be."

From the logs that we have, it looks like the first use of Rebirth worked correctly on the server, so the API route probably doesn't have a bug. I think the problem would have been just a client-side issue with the website not updating itself immediately to show that the first Rebirth had actually occurred. Most importantly, the cost of Rebirth on the website didn't change, so it looked like trying to use Rebirth again would still be free. I've confirmed in our logs that the second Rebirth was NOT free.

I'm marking this important priority because it can cause a player to use Rebirth twice, which means they spend 6 Gems more than they should.

The website is meant to reload itself as soon as Rebirth is used. I've just tested that with my 98089587-1bbe-4de2-92d3-0bbe76513a3f account on Firefox on Ubuntu and the reload worked, so it's possible that the reload is browser-dependent and/or intermittent. I'm asking hyunyeol for details about their browser and OS.

**Comment by Alys** [comment]
@hyunyeol has sent us more details:

"I was using Microsoft Edge on Windows 10 at that time."

"this problem did not occur the last time (Oct 2020) I used the Orb of Rebirth on MS Edge.
I also noticed the winter potions on sale around the time I used the Orb yesterday, which later turned out to be a bug & was fixed.
So there's a chance that this bug was associated with the temporary instability when the event started, and maybe it's already fixed as the other issues were treated."

**Comment by paglias** [comment]
I'm pretty sure it was due to some slowness on the server at the time the rebirth happened

**Comment by Alys** [comment]
We see this or similar issues happen often enough to be concerning, especially considering that when you use rebirth a second time without meaning to, it always costs you 6 Gems without any warning. It's a nuisance for user support because players often don't realise that they've lost Gems until some time later and we have to hunt back to work out what happened.

I wonder if we could prevent it completely by doing something similar to the `isFreeRebirth` check but with a much shorter timespan:
* When Rebirth happens, the code sets `flags.lastRebirth` to the current timestamp (in addition to setting `flags.lastFreeRebirth` when needed). That could be done at the same place as this code (outside this `if` statement of course):
https://github.com/HabitRPG/habitica/blob/7433eeb883887921f3d1406694789e0fce45ec49/website/common/script/ops/rebirth.js#L104-L106
* When the `rebirth` function starts, it checks the value of `flags.lastRebirth` and if it's within a few minutes of the current time, the function halts immediately. For example, that could happen just before the `notFree` check:
https://github.com/HabitRPG/habitica/blob/7433eeb883887921f3d1406694789e0fce45ec49/website/common/script/ops/rebirth.js#L14-L19
* It could show a message to the user saying that they've already rebirthed recently and that they should sync if they don't see the effects.

**Comment by kmacart** [comment]
Hi! Could I take this issue? I'm not sure if it's up for grabs or not so just let me know if it isn't!

**Comment by Basrara** [comment]
hi! i hope it's okay for me to post here. i'm not entirely sure if what just happened to me is 100% this issue or if there's something else going on, but it seems close enough to fit here.

so i just tried to buy the orb for free a few minutes ago, and i still cannot see any game effects. i refreshed the page afterwards multiple times, logged out and back in again, cleared all habitica-cache, and checked on my android app as well. everything still says that i'm a lv 101 rogue. i'm using firefox on windows 11.

i'm also currently resting in the inn. not sure if that could have something to do with it or no, just thought i'd mention it.

(i didn't send a bug report yet, because i don't want to double-post, but i can absolutely do that if it would help.)

(i'm dicedweller on habitica, 1643f1c4-3199-47b6-b0fc-99a3e567c092)

**Comment by CuriousMagpie** [comment]
@Basrara This is very helpful information, thank you! I know we had another user who recently had a similar issue and we had to manually update a few things on their account. If you need us to do that for you, drop us a line at [admin@habitica.com](mailto://admin@habitica.com). 

@kmacart Are you still interested in this issue? I know it's been a while since you've asked about this issue, so no worries if you're not.

**Comment by creaturebytes** [comment]
>UUID | 36976c15-5bcd-4197-965c-750d865abcd2
>User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 >Safari/537.36
>Level | 7
>Class | warrior
>Dailies Paused | false
>Costume | false
>Custom Day Start | 0
>Timezone Offset | -60
>Subscription | *\|USER_SUBSCRIPTION\|*
>Payment Platform | *\|USER_PAYMENT_PLATFORM\|*
>Customer ID | Gift
>Consecutive Months | 33
>Offset Months | 15
>Mystic Hourglasses | 0
>Description: "First I thought this was a glitch on my end because of slow internet connection. But then I saw @mirimanda posting about similar problems in the help guild today... Yesterday I used the orb of rebirth, as I finally was above level 100. The page refreshed, showing me Melior on a purple background for a while. Just as it has when I've used the Orb before. My class was changed to warrior and the mana bar disappeared. So I thought everything was fine. I had used a custom reward to save the gold I had earned lately, and after I used the Orb, I went to the FCV to give myself back the gold. I noticed that the gold value wasn't 0, but rather something like 0,00123456789... Didn't pay attention to the other values then. But then I looked at my notifications and saw a "choose your class" notification. I opened it and opted out. Then I noticed that my level hadn't changed. I was still level 102. Then I looked at the FCV again. My level said 102 there and the mana was at around 3. And I still had some experience as well, probably the amount I had accumulated towards level 103. I ended up using the FCV to reset my level, experience and mana to 1, 0 and 0. As long as I'm able to choose a class for free when I reach level 10, I'm fine with this workaround. But since it seems like I'm not the only one who encountered problems with the orb of rebirth yesterday, I thought I'd mention it."



>UUID | 35b85fa4-e47c-428a-ac11-11375dfce933
>User Agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
>Level | 100
>Class | warrior
>Dailies Paused | false
>Costume | false
>Custom Day Start | 20
>Timezone Offset | -60
>Subscription | basic_12mo
>Payment Platform | Paypal
>Customer ID | I-WBTV79XBV1D5
>Consecutive Months | 32
>Offset Months | 7
>Mystic Hourglasses | 5
>Description: "Hello, I used a orb of rebirth (2x yesterday in the afternoon, 1x today at 8:50 GMT+0100 time) - bought all three in the market shop and my account didn't get reset to lvl 1. I asked in Habitica help guild and they advised me to report a bug."
