### ISSUE TITLE
"Error request entity too large" - can't join / leave / edit / end challenge or guild

### ISSUE THREAD

**Issue by lefnire** [HabitRPG/habitica#1471]
```
2013-09-07T23:05:25.959760+00:00 app[web.1]: Error: Request Entity Too Large
2013-09-07T23:05:25.959760+00:00 app[web.1]:     at Object.exports.error (/app/node_modules/express/node_modules/connect/lib/utils.js:62:13)
```

---

_edit by admin_:
# What to do if you see "request entity too large" from any action involving a challenge or a guild:

**This problem occurs when guilds and challenges have many players in them.**

**It can be a temporary error, so try again a few hours later.**

**If you are trying to join a challenge, use [this "Join Challenge" form](https://jsfiddle.net/robcthegeek/qnc4g5g6/embedded/result/). It is likely to work in many cases but sometimes might also produce an error (due to the challenge being too large or popular, not due to a bug in the form).**

**If you're still unable to join the challenge, please comment here and include your User ID (see step 6 of the Help -> Report a Bug instructions), the URL of the challenge or guild (the URL will have a long string of random characters in it, such as https://habitica.com/#/options/groups/challenges/3b4f33e9-727b-4b9e-b41c-babfbcdb7ca4), and the action you were trying to take (e.g., join, leave, etc).**

**Especially comment if you are the challenge or guild owner and are trying to edit it but can't. Tell us what changes you need to have made.**

**If you are trying to close a challenge and cannot because of this error, make a note of the challenge's name, its URL, and the User ID and name of the person who is the winner. Add that information here and an admin will help you award the challenge achievement and prize.**

This is due to #5830 

##

**Comment by lefnire** [comment]
Happening very often right now. TMK it's not user routes, since User isn't an ngResource, meaning the full object isn't sent up with each request.

**Comment by paglias** [comment]
A group with all the members populated and 200 chat messages could be so big to break the server? Maybe if there's only a little ram avalaible

**Comment by lefnire** [comment]
512 RAM. You could right actually, since it's an ngResource it also sends up the populated members - in the case of parties, that could be pretty big. If many guilds / parties are chatting at once.... ok I'll look into this possibility first

**Comment by paglias** [comment]
This could be related to #1742, given how ngResource is implemented the
only way not to send the whole model is to use class level method, not
ideal but doable
Il 06/nov/2013 19:20 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
Class-level method is just fine, IMO. Good call!

**Comment by paglias** [comment]
Done for groups in https://github.com/HabitRPG/habitrpg/commit/a4951e151c93a848f5fcdd592bc97a36b2b24397, for everything except for $join which doesn't send anything big to the server and $save, we could remove the chat from it before sending but:

a-) we can't set group.chat = undefined untile we copy the group object to another var with angular.copy before doing that
b-) if something is updated server-side we would need to manually update the client side UI, with $save it's done automatically by angular

Will look into doing the same for challenges later

**Comment by lefnire** [comment]
awesome! you've covered most of these cases. I haven't seen the error for a while now, I'm going to close and re-open if I see again

**Comment by Typhlosaurus** [comment]
I was #5554 :-) I'm getting this after switching  to a larger party  and trying to join a large, non-party, challenge.

Reloading the browser and retrying, waiting for a day, reloading and re-trying not helping.

**Comment by marrowmalk** [comment]
I've been getting this error when trying to join a guild challenge for almost a week now — I've waited hours/days between trying again and it's still happening, unfortunately. The challenge in question is here: https://habitrpg.com/#/options/groups/challenges/b0060b72-9b8c-48cc-bc32-c326351c5b7f

**Comment by crookedneighbor** [comment]
@marrowmalk Are you still unable to join the challenge? If so, post your user id here and I'll add you. You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by marrowmalk** [comment]
Thanks so much! I am in fact still not able to join it. My user ID is
41596adf-4384-4600-ba96-6db7d5aa5294

**Comment by crookedneighbor** [comment]
@marrowmalk You should be added now, can you double check and make sure you received all the tasks?

**Comment by CantarellaMiyani** [comment]
Hi! I'm also getting this message when attempting to join a challenge, it's remained an issue after multiple reloads, and in multiple browsers. Challenge is here: https://habitica.com/#/options/groups/challenges/3b82f463-2e50-406c-9ec6-37b3cbfdfddf and my User ID is 7866d88c-1192-4bc2-b70a-87e3414397a2 . Any advice would be appreciated.

**Comment by crookedneighbor** [comment]
@CantarellaMiyani I've aded you to the challenge.

**Comment by CantarellaMiyani** [comment]
Thank you so much!

**Comment by marrowmalk** [comment]
Have been added successfully, thank you!

**Comment by minta98** [comment]
I'm having this problem too after trying to join this challenge:
https://habitica.com/#/options/groups/challenges/f5469002-b21d-4657-8450-2d194e846a73
my ID is 25dbf1f7-c126-482b-b597-7544dfe36ad8
I had the same problem with another challenge, but the day after I was able to join!
Is there anything I can do? Thanks

**Comment by paglias** [comment]
This is due to #5830, once that is fixed this issue should be resolved

**Comment by shanaqui** [comment]
Trying to close the Lifelong Learning challenge here: https://habitica.com/#/options/groups/challenges/feae0734-4e06-4fee-8ba2-8cfd554c40f1

BakkenFlow (1aa94f09-bc99-494f-bc9b-958594f86063) should be the winner, and the prize is five gems. 

I've tried it on a couple of browsers, refreshing, etc, and it's not working, so I don't think it's going to, and I did promise I'd close the challenge on the 1st September. Thanks!

**Comment by Alys** [comment]
@shanaqui I'll get that fixed for you after work in about nine hours, if no one else gets to it first.

**Comment by Alys** [comment]
@shanaqui The gems and achievement have been awarded and the challenge has been closed.

**Comment by kanabe** [comment]
Hi there! I've been trying to join this challenge, reloading the page every time, but it keeps on telling me that the entity is too large: https://habitica.com/#/options/groups/challenges/eef51c7c-3d99-405a-a662-2bd4744f9b54

Any help is much appreciated! I have been trying to join it for weeks. Thank you. 

My user ID is dc376f78-c16a-4807-a96d-2352417662b4

**Comment by UnexpectedMushroom** [comment]
I've been having this issue for the last few days, I'm unable to join [this challenge](https://habitica.com/#/options/groups/challenges/b96642a7-8e3b-4587-bfa8-3716b52b29ff). My user ID is 341218d8-cfee-4709-820e-0f710ac5f1cb.

**Comment by Alys** [comment]
@UnexpectedMushroom You're now in that challenge.

@kanabe I'm sorry, that challenge is too large for even admins to add you to it.

**Comment by UnexpectedMushroom** [comment]
Thank you ^^

Date: Thu, 29 Oct 2015 13:35:03 -0700

**Comment by Couvah** [comment]
Hey~ I can't join these challenges. ID: 4f4af460-3bba-4381-901d-0b1a83ae62f8
I guess the reason is too much people joins it. More than 700 people joins each of them~
Can you help me?~(●'◡'●)

![1](https://cloud.githubusercontent.com/assets/15520445/10863060/5f54d6b2-7ffc-11e5-9f6c-9d0c5fb734f9.png)
![2](https://cloud.githubusercontent.com/assets/15520445/10863061/5fbb5392-7ffc-11e5-9e58-7120e54234c3.png)

**Comment by Alys** [comment]
@Couvah I'm adding you to the challenges now. Please wait 15 minutes then reload the website. Tell me if you don't seem to be in either of the challenges correctly.

**Comment by Couvah** [comment]
@Alys  Oh I got it !~ Thank you very much!~ ლ(╹◡╹ლ ) HUG!~

**Comment by 225g** [comment]
I tried everything and waited a month. I still can't join. My browser is Palemoon. (I can't even sign in on Firefox.) The challenge is "10 habits you should do everyday".

**Comment by shanaqui** [comment]
@225g They'll need your user ID to try and add you to the challenge, but unfortunately @Alys already said that one is too big to add anymore people to.

**Comment by Lyranessie** [comment]
Help!
I can't close my challenge.
I've waited almost 4h before trying again and it is still giving the error.
I don't want any participant to be damaged beacause of it.

Challenge Name: Lumosity! October Edition
URL: https://habitica.com/#/options/groups/challenges/bf0ecb3c-6601-475b-9eee-f22f58bd0c60
Prize: 1 Gems (I'll give the +3 myself since it was supposed to be 4 gems)
Winner: Vilda a4150982-5f9d-49b9-a6b9-b5bf88ba711b

Thanks !

**Comment by Alys** [comment]
@Lyranessie The challenge has been closed and the 1 gem and achievement awarded.

@225g As shanaqui says, I'm afraid I can't help you with that challenge. 
@shanaqui thank you.

**Comment by shanaqui** [comment]
@Alys I'm omnipresent, you can't get away from me.

**Comment by debra-s-goldberg** [comment]
I waited a day and rebooted my computer.  Please add me to https://habitica.com/#/options/groups/challenges/745d9160-27cb-4ec9-8327-836963658727   ID: c8fda7cd-0374-4c82-bf15-de7586a4310e  Thanks!

**Comment by Alys** [comment]
@debra-s-goldberg I've added you to that challenge.

@shanaqui We wouldn't want to. :)

**Comment by ninetyd** [comment]
Thanks for the comment on #4800 @Alys. I can't join https://habitica.com/#/options/groups/challenges/f5469002-b21d-4657-8450-2d194e846a73. My ID is 97e0905f-cafa-44bd-848d-4816b24b5b4b.

**Comment by Alys** [comment]
@ninetyd I've added you to that challenge.

**Comment by Lyranessie** [comment]
@Alys thank you very much! _hug_

**Comment by debra-s-goldberg** [comment]
Thanks, @Alys!

**Comment by ninetyd** [comment]
Thanks a lot @Alys!

**Comment by ghost** [comment]
@kanabe @225g FYI, a new version of the 10 habits challenge can be found [here](https://habitica.com/#/options/groups/challenges/f32f5dc6-668c-4cec-972b-73a09abf1fe8), and there is another copy of it in the Library of Shared Tasks guild. They are both "permanent challenges" that are not expected to declare a winner, but you can pick up the tasks from them.

**Comment by kanabe** [comment]
@Cantras Thank you for the notice!
@Alys Thank you for doing your best in rectifying the situation.

**Comment by UnexpectedMushroom** [comment]
Can I be added to the [Happy List challenge](https://habitica.com/#/options/groups/challenges/2def5ee7-291b-4ec0-860e-33c2d3d09551) please?

**Comment by Alys** [comment]
@UnexpectedMushroom You should now be in the Happy List challenge, but let me know if anything doesn't look right.

**Comment by UnexpectedMushroom** [comment]
@Alys Thank you ^^

**Comment by UserAns22** [comment]
I'm trying to join this challenge:
https://habitica.com/#/options/groups/challenges/bc5a0cbf-de9e-4209-83f4-9af837681e8c
This is my user ID
a4406082-e17f-499f-869d-052b80ea1269
Thanks!
I've tried 4 times now.  Had this error.  Hopefully this thread isn't dead!

**Comment by Alys** [comment]
@UserAns22 The issue isn't dead. At the top of issues in GitHub, there's a coloured button that says either open or closed to indicate an issues status, and this one says open. Even when issues are closed, we still receive emails for all comments made. I've added you to the challenge.

**Comment by UserAns22** [comment]
Thank you so much!

**Comment by Rannera** [comment]
Hi! I can't join this challenge: https://habitica.com/#/options/groups/challenges/e6c1775b-c358-4e35-be89-c63a24d56322

Can you help me? My user ID is: b768b420-e492-4adb-bd06-324da530ebce

**Comment by Alys** [comment]
@Rannera That challenge was actually started more than a year ago and is due to be closed. The problem with popular challenges is that when many people join, the challenge becomes so large that it no longer functions properly, leading to the errors you saw. At that stage, it's also impossible for the challenge owner to close it. When we find such challenges, we typically close them on behalf of the owner.  We weren't aware of this one, so I'll add it to my list of challenges to be closed. I'm very sorry about the inconvenience! It will be a few hours at least before I close it, so you might like to write down the current tasks to make your own personal versions of them.

**Comment by Rannera** [comment]
Have done, thanks! :)

**Comment by cmlobue** [comment]
I've been trying for four days to end this challenge.  Same error every time.  

Name: Fall 2015 School Habit Challenge
URL: https://habitica.com/#/options/groups/challenges/7b9e1810-3d78-45db-abf5-7045cbe924cf
Award: 3 gems
Winner: moiseaux

Thank you!

**Comment by Alys** [comment]
@cmlobue Sorry about that! I think that challenge is actually due to be closed, and it's likely that the only reason it's still open is that the owner gets a similar error when they try to award a winner. I'll contact them about it. If they say that the challenge should be left open longer, I'll add you to it.

**Comment by Alys** [comment]
@cmlobue Can you please just completely ignore that idiotic message from me? :) I'm so used to people asking to join challenges that I didn't read it properly.... I'll close it for you now and award the prize to the winner. Thanks for letting us know about this. :)

**Comment by cmlobue** [comment]
@Alys I am the owner.  I know it's odd that I'm not also participating, but I am not a student myself.

**Comment by sadrithmora** [comment]
Hello,

I just tried to shut down the "2015 Movie Challenge" in the Tavern and award 5 gems to the winner, BlackUmbral. I did get an error, I don't remember what it was, but it did say something in the text about try reloading. When I reloaded, it seemed the challenge had disappeared for me, but the tasks remained with no indication they were closed. I did the "unclick done tasks" trick for broken challenges to be able to remove tasks, and it worked, but said that the owner had left the challenge and didn't show a winner. I'm not sure if it closed properly for anyone else, but the challenge did have a lot of users (~1300?). 

I believe the URL for the challenge was https://habitica.com/#/options/groups/challenges/638bf40e-49c4-445b-abfa-e40301c62ae9 but not positive as I can't go back and check now. I didn't get the user ID of the winner either. My user ID is 70665a76-c696-4e3d-a105-c9735640f1b0.

**Comment by Alys** [comment]
Sorry about that @sadrithmora! I've checked and the challenge has been closed. BlackUmbral does have the gems and the achievement.

**Comment by Typhlosaurus** [comment]
I'm afraid the Mobile App Download Challenge (https://habitica.com/#/options/groups/challenges/c14e8130-b22f-4e60-9bcb-7a34e5756829) is going to flood this issue with reports.  Certainly happening to me, so I imagine it will happen to a lot of others too (https://habitica.com/#/options/groups/challenges/c14e8130-b22f-4e60-9bcb-7a34e5756829).

```
POST https://habitica.com/api/v2/challenges/c14e8130-b22f-4e60-9bcb-7a34e5756829/join 500 (Internal Server Error)(anonymous function)
 @ app-027344d3.js:6s
 @ app-027344d3.js:6f
 @ app-027344d3.js:6j
 @ app-027344d3.js:7(anonymous function)
 @ app-027344d3.js:7j.$eval
 @ app-027344d3.js:7j.$digest
 @ app-027344d3.js:7j.$apply
 @ app-027344d3.js:7(anonymous function)
 @ app-027344d3.js:8o.event.dispatch
 @ app-027344d3.js:2r.handle
 @ app-027344d3.js:2
app-027344d3.js:32 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}responseError
 @ app-027344d3.js:32j
 @ app-027344d3.js:7(anonymous function)
 @ app-027344d3.js:7j.$eval
 @ app-027344d3.js:7j.$digest
 @ app-027344d3.js:7j.$apply
 @ app-027344d3.js:7s
 @ app-027344d3.js:6w
 @ app-027344d3.js:6y
 @ app-027344d3.js:6
```

Looking at the request, it includes full descriptions of all 1848 current members!

**Comment by sryshti** [comment]
Yes, I'm having the same issue with the Mobile App Download challenge
https://habitica.com/#/options/groups/challenges/c14e8130-b22f-4e60-9bcb-7a34e5756829

Already tried reloading and waiting a few hours and trying again.

**Comment by Alys** [comment]
@sryshti @Typhlosaurus There's a new copy of the challenge at https://habitica.com/#/options/groups/challenges/1aa1adbb-0df2-4bd0-a0df-590d4021b6fa so please join that one.

**Comment by Typhlosaurus** [comment]
Thanks @Alys - my concern was not so much getting on the challenge as that an easy to complete and well publicised challenge like this will display an error message to a lot of people - most of whom probably won't report it here.

**Comment by Alys** [comment]
@Typhlosaurus The old challenge now has a link to the new one so all players can find it.

**Comment by Typhlosaurus** [comment]
Great.

**Comment by DaBigKahuna** [comment]
User ID: da8b6751-8eec-4a7f-8630-cebb87df6b45

I'm getting this error when I try to start a Party Quest. I can't find a unique URL for the Quest.
Try multiple browsers on 3 different computers.

**Comment by Alys** [comment]
@DaBigKahuna It's because the party is very large (125 members) and the site is under more load than usual at the moment, so when the site tries to update all the party members' accounts with the quest information, it times out. Please try again in a couple of hours and tell us if it still doesn't work.

Note that this is probably going to happen again in future, due to the size of the party. I recommend that the party leader removes inactive players, which will help to speed up all actions involving the party, and should give better site performance for all party members. It might also allow quests to start automatically since active players will accept or reject the quest invitations. If the leader wants to, I can remove the players that haven't logged in to Habitica for a certain number of days or weeks - the leader can choose how long. If the leader wants me to do this, they should PM me within Habitica so that I can confirm from their User ID that they are the leader. Note that this action won't delete the accounts of the inactive players; it will just remove them from the party.

**Comment by robcthegeek** [comment]
Any/everyone that has been trying to **join** a challenge - please check [this out](https://github.com/HabitRPG/habitrpg/issues/6855#issuecomment-195689823).

Hope it helps!

**Comment by melissamcewen** [comment]
Can someone help me end this challenge? 

Nevermind: Forked @robcthegeek 's form to end it
https://jsfiddle.net/0LtsfpzL/1/

**Comment by crookedneighbor** [comment]
This should be fixed with the v3 api. If it is not, please report here.
