### ISSUE TITLE
Drops stopped coming

### ISSUE THREAD

**Issue by b4silio** [HabitRPG/habitica#1498]
As I understand (or at least my experience has been so), drops have been tied to Dailies being completed, and capped to one drop per day (with the already reported skewedness in the eggs / potion ratio).

However, 3 days ago I droped yet another dragon (have almost a full set), tried to hatch it with a pink cotton candy potion (which I had in my inventory), the pcc-dragon hatched (and is currently in my stable) but the potion and the egg remained.

Ever since I don't get any more drops of either eggs or potions. I can't re-hatch the dragon (I already have all the potion/egg combinations) and don't know whether this would restart my drops!

![habitrpg-inventory](https://f.cloud.github.com/assets/4587092/1108433/0089921c-196f-11e3-91ae-6b95ffa67284.png)

**Comment by wc8** [comment]
Are you aware of the site rewrite?
If not some features are still being ported there, this might be one of them. 
(P.S. just to let you know, not to say you shouldn't report it)

**Comment by paglias** [comment]
@wc8 I ported it so it should work :( @b4silio so it's working but not
removing the eggs once hatched, right?

2013/9/9, wc8 notifications@github.com:

> Are you aware of the site rewrite?
> If not some features are still being ported there, this might be one of
> them.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lefnire/habitrpg/issues/1498#issuecomment-24094874

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
Drops are still coming, people just aren't notified on the client. I've
seen a lot of people working with eggs & potions in the new site, so I'm
quite sure they're going through. I'll be revisiting this feature very soon
in any case, and will be able to dig in to see what could be going wrong

**Comment by b4silio** [comment]
Thanks!
Indeed I knew about the site rewrite (you guys are awesome btw!) but had not necessarily linked that to the issue. Indeed It would seem that I am dropping stuff, simply not noticing that as lefnire suggested!
I'll just wait and hope for eggs then!

Thanks!

**Comment by paglias** [comment]
So it is solved for you or still you have problems with the fact that egg/potion didn't dissapear after hatching?

**Comment by b4silio** [comment]
Unfortunately I cannot say if the egg/potion disappears because I cannot hatch any pet that I don't have yet (the system does not allow me). So I'll have to wait until I get something hatchable!

As for the drops not coming, indeed, the problem is solved, the drops are coming, just without a notification appearing.

**Comment by lefnire** [comment]
Can we give you gems for science?

**Comment by b4silio** [comment]
ehehehe always! I can test right away.

**Comment by b4silio** [comment]
Mmmh decided to use some of my gems to test, and indeed the problem persists: The pet has been hatched, and right away the egg and potion disappeared, but when I reloaded the potion and egg were back and the pet was still there.

**Comment by lefnire** [comment]
compensated gems, thanks for the info. Will look into

**Comment by paglias** [comment]
@b4silio seems a problem of thing not being persited. 

I'm sure some times ago it worked, @lefnire did you changed something in the schema for items.eggs & items.hatchingPotions?

**Comment by b4silio** [comment]
Mmmh reloading right now, the egg and potion have disappeared for good. And they stay away (tried from beta as well). This did not happen the first time around (2 days ago).

Is it a question of unfortunately timed refreshes?

**Comment by lefnire** [comment]
Nothing in schema, but this could be related https://github.com/lefnire/habitrpg/commit/55dffcc317c702e226b4c2f8a12bab73d29dcfdd - (was a required fix for #1476, but did I stop on new toes?)

**Comment by paglias** [comment]
Bugs not reproducible, I hate you!

Which means that I got a potion & an egg, used them, now I have a pet and the potion & egg are correctly gone.

**Comment by Aiseant** [comment]
I do have this problem too : I hatched two pandas today, still have eggs and potions

**Comment by Jajoto** [comment]
I still have problem with receiving eggs. I don't have any egg drops but loads of potions aside from random chance.
![inventory](https://f.cloud.github.com/assets/5342706/1122910/c9f303fa-1ae5-11e3-804f-80e47e31b581.jpg)

**Comment by b4silio** [comment]
It's also a question of perception: If you have 20 pets, it means you've received at least 20 pairs of eggs + potions, but since chances are 1 to 2, you should have received 20 eggs + 40 potions. While you get rid of eggs right away (you hatch them as soon as you can) the excess potions just remain there, and will always remain there, since statistically you'll always receive more potions than eggs...

**Comment by Jajoto** [comment]
But the ratio is 50/50. See here: https://github.com/lefnire/habitrpg/issues/1048?source=cc

Here is the script (line 136): https://github.com/HabitRPG/habitrpg-shared/blob/master/script/algos.coffee#L136

And the problem is not "you'll always receive more potions than eggs" because I do not get eggs at all.

**Comment by baimeeker** [comment]
Going back to streaks.  Previously, it was typical for 21+ day streaks to result in a drop a high percentage of the time and for those drops to include more rare items like gold or pink potions. These days, I rarely get a drop despite 4-5 21+ day streaks in dailies. When I do, it is usually a potion, and that potion is almost always white for some reason.

Also my 21+ day streak achievements are not updating to show that I have more of them.

I'm patient, and I know you are still making changes. I just didn't see this particular issue listed anywhere.

Username: baimeeker

**Comment by Shaners** [comment]
I think eggs are dropping but are being deleted soon after. A fair amount of people are reporting not getting any eggs since the rewrite and with the notifications not happening I think it's possible that <em>they are</em> getting egg drops but by the time they view inventory they have been removed. This could also be increasing their daily drop count making it appear like they aren't getting <em>any</em> drops. It does not seem to affect potion drops or eggs collected before the rewrite. 

@lefnire @paglias I can't confirm this until tonight and even then I have a busy evening so if one of you wanted to test it might be something good to look into. Basically with my local I removed the daily limit and made an item drop on every completed task. I noticed that I did get some eggs but after going to tasks, completing more, and returning to inventory some of the eggs disappeared.

**Comment by paglias** [comment]
@Shaners what is happening, I think, is that: when you complete a task/todo/habit a request is sent to the server which then sends back the whole user object which when received by the client overrides the current user object.

So if you click too fast it may happen that a server response override the user object with an older version of it and some changes may get lost.

Try clicking very fast an habit + action, then release it you'll see that sometimes the experience decreases a little, it returns to an older version of the user model.

Anyway I don't have time to test it, today

**Comment by Shaners** [comment]
The thing that worries me is that I haven't really been able to find anyone in tavern chat that has gotten an egg drop (without using it right away) since the rewrite but they seem to be flush with potions. If it's a server override with an older version wouldn't it affect potions in the same manner?

**Comment by paglias** [comment]
The code for eggs/potions drop on habitrpg-shared is exactly the same, sincerely I don't know

**Comment by lefnire** [comment]
definitely some funkiness going on with eggs, I'm going to check into this soon

**Comment by lefnire** [comment]
ok cool, referenced fix above #1520 looks like fixed the issue (after some local testing). Re-open if we experience this still

**Comment by lefnire** [comment]
btw @Shaners the best way to test this is: comment out this line https://github.com/HabitRPG/habitrpg-shared/blob/rewrite/script/algos.coffee#L124 , "restore streak" on a daily to 100, check & uncheck it over & over

**Comment by Shaners** [comment]
@lefnire booyah lets do some testing. Maybe the way I was testing before was breaking things.
