### ISSUE TITLE
Lost egg when I got another egg

### ISSUE THREAD

**Issue by kelseyr713** [HabitRPG/habitica#1561]
Last night, I got a fox egg. I don't have any hatching potions yet, so I couldn't do anything with it. I got a dragon egg today. When I went to check my inventory, the dragon egg was there, but the fox egg was gone.

Thank you for your help! :)

**Comment by Shaners** [comment]
Thanks for reporting this! What level were you at when you got each egg?

This is concerning since it always seems to be eggs getting killed.

**Comment by kelseyr713** [comment]
Level 4 for both eggs! Right now, I'm at 82/180 for level 5. My user ID is 7aace286-d821-4d37-9a74-a58d484e0519 if you need it/that would help.

**Comment by katfang** [comment]
Had a similar issue. I hit Level 4 and received a Wolf Egg and a Desert Hatching Potion (as far as I can tell, it was for leveling, but I wasn't looking to closely). Later, closed the window and then went back to HabitRPG and got a notification that I had unlocked the drop system and now had a Flying Pig Egg. No Wolf Egg anywhere, but I still have the Desert Hatching Potion

**Comment by paglias** [comment]
@lefnire could it be https://github.com/HabitRPG/habitrpg-shared/blob/rewrite/script/algos.coffee#L180 that should be an array so multiple drops don't override themselves? We discussed that a while ago when rewriting the site I think

**Comment by ACRPG** [comment]
i had about 6 eggs saved in my inventory, and today when i logged on, the page acted as though i was new to the system ("you've unlocked the drop system!") and deleted all my saved eggs. :( 
everything else (e.g., all the health points i've lost, lol;  my level; my armor, etc) seem to be the same
i'm on level 22

**Comment by kriscrat** [comment]
Same happened to me. Still have all my potions, but all my old eggs disappeared. 

From my Android phone on T-Mobile. The first nationwide 4G network.

-------- Original message --------

**Comment by strawberryjello** [comment]
My experience was similar to katfang's. I got a panda cub egg at level 4, then after logging out and back in I got a dragon egg (I might have leveled a little in between); the panda cub egg was gone. After another re-login, the dragon egg was replaced by a bear cub egg. This happened all in one day, within a few hours; so far it hasn't happened again. I still have the bear cub egg.

**Comment by ACRPG** [comment]
It just happened to me a second time. Once again I got the "new user" messages (e.g. "Use the party system!").

**Comment by joernal** [comment]
i had the same problem as kelseyr713
i had a dragon egg earlier and i didn't hatch it because i didn't have any potions.
later, i found a flying pig egg and i just noticed my dragon egg missing
i was also at level 4 during this whole ordeal

**Comment by ACRPG** [comment]
This has happened to me about ten times now. And I think that Issue #1610 sheds light on exactly _when_ it's happening. Occasionally, I log into Habit on a less-used computer, and then log in again on my old, mainstay computer.Upon the login to the main computer, I get hit with the new user messages and my eggs are deleted.

**Comment by Shaners** [comment]
@ACRPG when you see the tour how do you end it, do you press end tour or just hit next? Are you using beta.habitrpg.com or just habitrpg.com?

**Comment by paglias** [comment]
@lefnire it could be https://github.com/HabitRPG/habitrpg/blob/master/public/js/services/guideServices.js#L115, it' quite sure it. But i don't understand why @ACRPG flags get resetted. It should be fixed with https://github.com/HabitRPG/habitrpg/commit/08fd4a865a21be0f8b04078ae11a5c81887ec6be which doesn't reset user's eggs if they are already there.

@ACRPG beside the new user message you also get the "drop enabled" message?

**Comment by lefnire** [comment]
Man, this was a pretty bad bug. I've pushed @paglias's fix. If anyone effected wants gems to buy back their lost eggs / pets, reply with your UUID and I'll hook you up.

@paglias should we close this one, or should we leave it open to verify it doesn't happen again?

**Comment by kelseyr713** [comment]
Thank you, everyone! I'm glad I could help find this. :) I ended up finding another fox egg, so I don't need any gems or anything. :)

**Comment by ACRPG** [comment]
I just tested it out again -  I signed into Habit on my secondary computer, then closed out Chrome and came back to my primary computer and logged in. Sorry for the delay.

Result is that I got the splash screen "Drops Enabled!" which seems a little different than what happened before - I don't remember the big splash screen, just smaller notes, but maybe my memory's off on this. 

To answer your previous questions:
- I'm using habitrpg.com (not beta)
- I get the "drops enabled" message and the smaller "Customize your avatar" and "Item Store Unlocked" tabs. 
- I don't see an "end tour" option, there's just small tabs with options to "Customize my Avatar", which sometimes I close out and other times I just ignore (like if I'm going over to the Groups area, then I can just click on my avatar to switch over the second set of menu options, and the "Item Store Unlocked" tab will just disappear). I'm lazy and I don't want to click all the "Close" buttons.
- My UserID is 03a02bbb-d54d-48c6-96f9-117c804d8590
  I did lose a half dozen eggs when it first happened, but since then have been cautious about immediately transforming each egg I get immediately. Actually, I never receive eggs except when I have this error occur and I accidentally "enable" the drops system again. The rest of the time I just get hatching potions. So as a result I have quite a cache of 20 hatching potions. 

Thank you all for your help and work!

**Comment by paglias** [comment]
@ACRPG next time you'll get an egg, could you try switching pc to see if they still get deleted? They shouldn't, it's just to be sure.

@lefnire well we stil have this problem about getting the "drop enabled", etc.. messages

**Comment by ACRPG** [comment]
So I just tested a few more times (signed in on computer #2, closed browser, signed in on computer #1) - and this time, no splash screen or newbie tour notes! Bravo! 

@paglias, per your request, I'll test things again once i get an egg to see if it gets deleted. but as i noted above, i almost never receive eggs. i now have 21 potions and 0 eggs, lol. if @lefnire restores a few of the eggs i lost when this problem first emerged, i'll test it out for you.

**Comment by paglias** [comment]
Good to know @ACRPG ! (Even though sincerely no fix was specifically made for the splash screen/tour bug)

About egg:potions ratio there has been a complex discussion at #1048 with some extensive testing made by @Shaners (https://github.com/HabitRPG/habitrpg/issues/1048#issuecomment-24931248) that showed no problem.

Until today I had 12 potions and no eggs as you, but I just got a lion egg, wait some time and you'll find some for sure!

**Comment by ACRPG** [comment]
Alright, I received an egg on Computer #1, then logged in on Computer #2, and then back in on Computer #1. The egg remained in my inventory! Looks good so far!

**Comment by lefnire** [comment]
@ACRPG if you, or anyone else on this thread, wants some apology gems hit me with UUID. Sorry everyone, and thanks @paglias!!

**Comment by ACRPG** [comment]
Hi @lefnire, thanks for the offer. My User ID is 03a02bbb-d54d-48c6-96f9-117c804d8590. Is that all you need? 
Thank you all!

**Comment by lefnire** [comment]
There ya go

**Comment by ACRPG** [comment]
wow, thanks so much, @lefnire!
