### ISSUE TITLE
Challenges not filtering by Groups/Membership

### ISSUE THREAD

**Issue by bobbyroberts99** [HabitRPG/habitica#1669]
Not sure if this is live yet, but clicking box doesn't select box or filter by that selection.

![name004](https://f.cloud.github.com/assets/4084120/1441594/0eb771da-41ae-11e3-90a5-f598348c8a9e.jpg)

**Comment by lemoness** [comment]
Agreed. Clicking "participating" or "not participating" doesn't at all affect the list I see.

**Comment by lefnire** [comment]
shoot, it does for me. ok, diagnosing

**Comment by bobbyroberts99** [comment]
It works for me now too. On a related note, the drop down list of groups to assign to a new challenge wasn't populated the first time I tried to create a challenge using Chrome. It works now though on both Safari and Chrome (Mac 10.8.5).

![name005](https://f.cloud.github.com/assets/4084120/1441916/835c2fe4-41b3-11e3-9055-00d6f9691e08.jpg)

![name006](https://f.cloud.github.com/assets/4084120/1441924/98158ebc-41b3-11e3-89aa-7c2358e35acf.jpg)

**Comment by lefnire** [comment]
OK, this may have been fixed in https://github.com/HabitRPG/habitrpg/commit/d2c50dc02fb76987b5ae9d62a7867d400d7e135f then. Re-open if we experience either of those issues again

**Comment by paglias** [comment]
I still have one blank checkbox

**Comment by bobbyroberts99** [comment]
This looks good on my end.

**Comment by lefnire** [comment]
yeah me too. @paglias can you try on the recent push?

**Comment by paglias** [comment]
I still have an empty checkbox (the empty option when selecting a group for the challenge is due to angular)

**Comment by paglias** [comment]
![selezione_001](https://f.cloud.github.com/assets/589911/1452680/c9f59558-42da-11e3-98f1-3bf968041ecc.png)

**Comment by paglias** [comment]
It's happening only on challenges.habitrpg.com, can't reproduce on my local installation. It's probably a corrupt database record

**Comment by ghost** [comment]
I've got a blank checkbox on HabitRPG.com's challenges page myself. Tried in both Chrome and Firefox. Almost definitely a problem with the site's DB.
