### ISSUE TITLE
Admin tab throws 503 error on first visit

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica#1877]
Firefox on Win7. Nothing notable in the JS console.

When I first visit the Admin tab after a bit of absence, the blue loading bar takes a good long time (15 seconds or so?) to traverse my screen. When it finally wraps up, the contributors list remains empty, and a squashed alert box throws a 503 error:

"Application Error

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

If I then reload the page, the list of contributors comes up fine.

**Comment by lefnire** [comment]
fixed, i was running `User.find({'contributor.level':{$exists:1}})`, which was taking too long to compute. I just need to add an index on that field `db.collection.ensureIndex({'contributor.level': 1 })` so it would load faster. Second load worked because mongo caches queries

**Comment by SabreCat** [comment]
Today I also saw this happen on one of my Guilds (one with much less activity/fewer members than others, oddly enough). Separate issue worth writing up, you think? Assuming I can reproduce it.

**Comment by lefnire** [comment]
hmm, that's very strange.. `db.groups` has indexes on `type` and `members`, which is what would have been the issue if these problems were similar. I think make a new ticket if it crops up again

**Comment by SabreCat** [comment]
This is still happening to me on the Admin page. Fix wasn't quite sufficient? Or hasn't been pushed yet?

**Comment by lefnire** [comment]
I saw it happen as well. Fix is already live, I'll have to revisit later

**Comment by SabreCat** [comment]
Hasn't been happening lately. Will reopen if I see it occur again.

**Comment by lefnire** [comment]
Happens for me still. What makes it ok is if someone loaded it before you, and Mongo caches the query. It's just a bad mongo query, or a bad index / compound index. Plan to visit when we add Hall of Heroes stuff
