### ISSUE TITLE
503 / "Application Error"... Sudden death, lost levels / inventory

### ISSUE THREAD

**Issue by Badbeagle1066** [HabitRPG/habitica#2601]
I went to bed last night with all dailies and good habits grey - awoke this morning to be told I was dead and would lose ALL my gold, 1 inventory item and 1 level.  I lost all my gold, all my levels and all of my inventory - on a perfect day! So depressing. Please help!
##

**Comment by chickiedear** [comment]
I signed in to the Inn last night, and I also woke up "dead". Lost all my gold, 1 inventory, and 1 level.

ETA: I was not in any quests, so I don't think there's any other reason why I would've lost enough health for that.

**Comment by wc8** [comment]
@Badbeagle1066 check for the Fix Values options on the settings page, I'm not sure if you can Fix Gold, though @lefnire?

**Comment by lefnire** [comment]
Before getting into this, note: you can restore your character's values at [Settings](https://habitrpg.com/#/options/settings/settings) > **Restore Character Values**. If you lost gear, restore your GP and buy back.

Alright, **lots** of reports of unexpected death. The site has instability going on lately, read all the [details here](https://github.com/HabitRPG/habitrpg/issues/milestones). There's a theory in that description that says site lag (caused by code bottlenecks or instance crashes) results in one of two things: (1) an operation getting duplicated; (2) an operation not going through. 
- Duplicate operations: multiple random tasks being created with a strange title; one [-] habit click killing your character; cron repeating, killing your character; one item-purchase knocking you back a ton of gold
- Op didn't go through: nothing happens.

However, some of these reports suggest sudden death in the middle of the day, on a √todo (or any positive action), well after they'd had time to calibrate - which wouldn't fall in this grand theory. Since they started happening at the same time, I _feel_ like they're part of the same bug, so I just want to be certain:

Anyone experiencing this bug, are you _sure_ it wasn't a result of any of the following:
1. You clicked a -habit (even just once), and died suddenly (duplicate ops)
2. You died unexpectedly at the beginning of the day (cron got duplicated)
3. Big one: are you sure your actions went through the day before? ie, had you refreshed the page at any point the day before, and yes indeed things were still checked? My hunch is the ops didn't get through, it looks like they were checked but a refresh would show they aren't. Come next day, nothing was checked.

Obviously this whole deal is unacceptable, and we're working hard to fix these bugs. Just trying for a "grand theory of unification" here, given the timing

**Comment by lefnire** [comment]
Have some useful info from other tickets I'm gonna drop into here, so we can track them in one location:

@katfang:

> The short summary of the bug (I believe that) I'd like to report is that I deleveled twice in one "death." I'll include the longer explanation because a lot of different issues seemed to have hit me at once and are all related to death. The closest other bug I can find to this is #2630, which has a similar stew of problems and also says some things have been double counted due to internet slowness, but because my [first] death can be explained, I decided to start a new issue.
> 
> Last night, when I fell asleep, I was level 20. This morning, I logged on with just 4HP after my dailies and the Trapper Santa calculated damage on me. Just now, I refreshed the page and found that I had died, lost an item, and subsequently am now level 19 (due to a friend, Trapper Santa dealt me another 7 damage). Only then I refreshed again, and found I was at level 18. I later found out that I had another HabitRPG window open, so maybe death hit me twice because both happened to be syncing or something. After 3 more refreshes (with 1 window open), I seem to be stably at level 18.
> 
> There is, as far as I can tell, nothing that justifies two deaths, but it is also not random.
> 
> ---
> 
> So that's the short of it. The extended version of my sadness is that I seem to have actually lost 3 levels, from 21 to 18. As I mentioned, I was 4HP after my daily damage / Trapper Santa was calculated. I quickly finished a bunch of tasks, and hit 21 with a _huge_ sigh of relief. Around the same time (I'm pretty sure this was not at the time I leveled to 21, but shortly afterwards), the #2554 issue came up for me (but I ignored it).
> 
> A few hours later, I get back online to check off another box, and I receive the death report that brings me down to 19. It said I lost my candy cane robes, and my candy cane robes were back on my rewards list (and thanks to #2663, because otherwise I definitely would have freaked out).
> 
> I later find another HabitRPG window open that says I am at 18. Hoping that the situation would resolve itself in my favor, I closed the window that said I was now at 18, and refreshed the window that said I was at 19, the one in which I received the death report. Well, I'm still at 18, but my candy cane robes are back. My hat, however, is gone. Actually, both my latest hats (candy cane and cornuthaum) have disappeared. Seems I've been hit by #2471 as well.
> 
> Here's the explanation of what I think happened to all the levels.
> 
> 1) Level 21 might not have actually registered on the server. This would cause the 21 to 20 "death."
> 2) Prior to my level up to 21, I was at 4HP. The Trapper Santa dealt 7.2 damage due to a friend. As far as I know, this was _after_ I leveled to 21, but checking the time at which that damage was posted, it might have happened before. In any case, this might have caused the 20 to 19 death.
> 3) I later found out I had another instance of HabitRPG open. This might have caused the 19 to 18 death.
> 
> With only one HabitRPG open, I refresh, and I am stably at 18 with 50 HP with 0 XP. 
> 
> What I think should be true is either that I should be Level 19 with an item gone and non-zero XP if the 7.2 damage hit before I got the XP to level to 21 from 20. Or I should be Level 21 with my candy cane hat with 7.2 HP chunked out of me. It would also be awesome if I could get back to level 19 [or 21 with my hat back], but in any case, I hope I've shed some more light on some of the issues surrounding death.

@aurakami:

> Hey all! My partner (who doesn't have an account on here, thus me posting) just randomly died. It stated he took 17.4 damage (though he may or may not have had more health left than that) and while our party is currently in a quest, there was not enough damage (1.4) to warrant his death. He has no dailies to detract from his health as well, just habits and to-dos.
> 
> As a side note, is it possible to give him certain armor pieces back? He worked really hard to get all the special holiday outfits of each class and dying caused him to lose some of those pieces. (Though the death message stated that his Yetti Tamer Robe was "broken" however it still seems to be there.)
> 
> To quote him:
> "Snowflake Shield, Ski-sassin Parka (whatever the head/helmet of the ski-sassin set is).
> I also have a bunch of garbled habits added to my habit, all green colored.
> I also have To Do's that I did a while ago, reappeared in my list of To-Do's."

@mentalisttraceur:

> Just registered an account on GitHub (surprising I didn't already get around to it, given that I am involved in software development with a couple of open source projects...), I'm the person whom the above bug report concerns.
> 
> Further details: We were having internet issues today, including general lagginess and slowness, and at least once over the last couple of days I had a glitch where things seemed to get double counted, with the second count being seemingly delayed by a while. I didn't bother to debug because I am fairly busy and it wasn't significant enough to effect my gameplay...
> 
> Anyway, earlier today I had gotten the Snowflake shield, completing not just the Healer limited edition equipment, but also finishing getting them for every class. (I was saving Healer for last since that's the class I wanted to stay at long-term.) I equipped the Healer gear, but then later when my partner (aurakami, the reporter of this issue) was on HabitRPG from her account, she did not see my outfit update from the previous (I was wearing the Candycane Mage holiday edition set previously), even after several reloads on her age (and no, I do not have Use Costumes turned on). So I thought, maybe there was some hiccup with stuff updating from my browser, so I went and reloaded my HabitRPG page. ..a-a-a-and that's when I got hit by the "You died" thing, out of no-where. I'm almost dead certain it said I took 17.4 damage (I had at least that much life, possibly more, I don't remember). There were also other notifications under the -17.4 Health one, but I don't remember what they were. I was too stunned to think to take a screenshot before the notifications faded, but I did think to take it right after. Which is the first screenshot you have in the above report. I opened another tab and also loaded up habitRPG, hoping maybe it was a really messed up glitch but that it didn't "stick". No joy, it loaded to the same you died message. So I clicked through it in that new tab, and it proceeded to take away all of my gold/silver, add 50 health, and claim that my Yeti Tamer Robe broke. Checking inside my inventory/equipment however, I see that I still have the Yeti Tamer Robe (I dare not click on it though, in case more glitchy-ness deprives me of it or something else), but that the Snowflake Shield and the Ski-sassin Hood (or whatever the helmet one is called - I just looked up 'parka' and I realize now that the head piece is not called the parka, but I don't recall what it is and I don't want to spend another 3 gems on a class switch just to get back something that shouldn't have been taken away in the first place) are both missing. The Snowflake Shield still shows up on my avatar as if equipped but is not in my inventory (in the second screenshot above you can see that it still looks as if my avatar has it equipped but that it has re-appeared in my Rewards, suggesting I no longer have it.
> 
> My suspicion is that somewhere along the line, some events (me hitting minuses and pluses on my habits and getting some todo's done) go counted once, but also got queued up, and that a page reload somehow brought the queued up stale instances of the events out, and ran the effects for those again.
> 
> Further information: in the day or so leading up to the above situation, I was also having (just as mentioned in the referenced issue #2663) occurrences of issue #2554. I don't know if that helps you guys pinpoint the issue any.
> 
> Also question: I see in the first referenced issue's comment that it says special edition items will always be re-buyable if they were bought during the special edition period. That's great. Just to confirm though, that applies to special edition items from another class right? (i.e. I lost both a Snowflake shield and a Ski-sassin hat/hood/whatever, and am currently a healer. If I remain a healer until after the 31st, then switch back to a rogue sometime later, I will still be able to re-buy the Ski-sassin head gear, correct?)
> 
> Possibly related, I also just noticed that all of my stats on my habits got lost - I just deleted all of those garbled automatically added habits, so I don't know if maybe that data got moved into those habits, but yeah. The only stats seem to be two data points from 2013-12-27, which is I think when I first started using HabirRPG consistently and set up all of those habits, and one's from today or so. (Except Habits I added very recently, like on the 30th, so after the random death, still have their stats. Ones I added recently but before the random death, Habit garbling, etc, have no stats on them.)

**Comment by eiron** [comment]
Just throwing down here that I am getting a lot of 503 errors. There does not seem to be any one thing that sets it off. It can be after checking off a task, after using an egg-potion combination or even occasionally after simply loading a page. I have some tasks that are checked off, but then are not on refresh, and some that somehow have higher streaks than I have days since Rebirth. It is all very peculiar.

**Comment by deilann** [comment]
Same here.

Whenever I see a 503 error, I make sure to refresh and fix anything that
didn't get properly saved. It's helped a lot with making sure everything
saves before cron.

**Comment by Silverei** [comment]
Woke up today to find that I've died, lost my gold, and lost my Wizard Robes. However, I ticked off all my dailies before my day reset and I was at full-health. I double-checked Vice to make sure it wasn't because of quest damage too. 

I find that I'm still in the quest (still listed under the participants that is), and that I'm still wearing my Wizard Robes both as a costume and as an actual equip. Some dailies I'd ticked off the day before were also still ticked, despite not using the Inn. 

It's a bit depressing, since I was at level 64 and I was close to leveling:'(

**Comment by wc8** [comment]
@Silverei no dailies, no quest damage, no bad habits: if you can remember the approximate numbers, go to Options > Settings > Fix Values

**Comment by Draayder** [comment]
Mine was weird because the tasks remained checked the following day but didn't count for the previous day, almost like cron didn't happen. I lost my absurd party robes which showed up back in my shop and on my character on refresh and then disappeared from the shop without be buying them on another refresh only to be replaced with one of the mid-tier rogue hoods. I've fixed all my values at least and thankfully you don't get kicked from quests for dying yet, though my party member did have to eat a lot of damage because of it.

Edit: Just realised that several of my to-dos were also duplicated, checking off one thing on the checklist also affected the duplicate.

**Comment by Badbeagle1066** [comment]
Full health last night - dead this morning.  Multiple 503 errors.  No gold and my candy cane staff is gone (waaaaa). Only lost one level this time which an improvement over the 7 I lost last time.  I also have an ongoing problem of dailies only partially resetting - sometimes my screen looks like it is trapped between two days.  I also have to reset my streaks almost daily (I have given up on many of them).  Google Chrome - let me know if I should include any other info.

**Comment by deilann** [comment]
Dailies not resetting is another issue. If you search Dailies not
resetting, you can find the ticket. (Sorry, replying from email, so can't
search for it.) You should be able to repurchase your Candy Cane Staff,
even though it it past the event date. You can use Fix Character Values to
give yourself back your gold (and the gold for the staff) and your XP.

**Comment by ony** [comment]
My friend were dropped from 28 level to 16 this morning (with dead) and lost special gear (from New Year).
Used Google Chrome at netbook and notebook (both periodically fall asleep). My account also hit by -38 HP (as result dead an -1 lvl) while I did complete my dailies as usual.

Tried to export history into CSV, but I can't understand how it is generated because when I exported another history.csv after marking one of my "habit" it simply added it to history as if I never clicked "+" on it before.

**Comment by ACRPG** [comment]
Lost wrong piece of gear when I died - 
I lost all my gold, 1 level, and the interface told me I'd lose my yeti-tamer spear. However, I still have the spear. But I HAVE lost my snowflake robe instead, and I don't see anyway to repurchase it.

**Comment by deilann** [comment]
@ACRPG Are you a healer? You can only buy gear for your class.

**Comment by ACRPG** [comment]
Hi Dielann, thank you - yes, that's half of the problem! I now understand that I'll only be able to buy the item back once I'm a healer again. But there's still the unexplained issue that the interface told me I'd lose one item, but I lost a different one in actuality.

**Comment by deilann** [comment]
Yeah-- there's another ticket for that. Can't search for it at the moment,
about to sleep. :)

**Comment by tanzensehen** [comment]
I suddenly died today, despite having checked my dailies and having full health yesterday. I was also supposed to lose my Absurde Party Robe and instead one of my helmets were gone - I am concerned because the Yeti Tamer Robes also suddenly disappeared the other day.

**Comment by deilann** [comment]
The being told one item went away and another really getting "broken" is a
known bug. It's a discrepancy between the server and your local side. We're
having server issues-- the best way to keep this from happening is to
refresh your task list before the end of the day. Then, you should be able
to tell if anything wasn't checked off server-side, even if you checked it
off. Also, always remember that if you encounter bug related death, you can
go to Settings > Site and click on "Fix Character Values" to put yourself
back where you ought to be.

**Comment by goggi-** [comment]
I died a sudden death on Friday morning after logging in via the unofficial habitRPG app by MagicMicky. When I checked on the website I had lost the usual stuff (one level, gold, one item). Only problem is that I lost my flappy dog ears and I'd really like to have them back. Is there any way to get them again?
Another issue that happend in connection with my sudden death is this: "Selaz attacks Hedgebeast for 12.2 damage, function (lang) { if (vars == null) { vars = lang; } return i18n.t(string, vars, lang); } attacks party for 0.0 damage." No idea what it means...

**Comment by deilann** [comment]
Are you using beta, goggi?

Also, you can repurchase the dog ears if you're still a healer -- and
that's actually what you lost. Sometimes it says you lost one thing when
you lost something else entirely.

**Comment by goggi-** [comment]
Oh, I totally forgot ab out that! Yeah, I am.

**Comment by deilann** [comment]
Stuff on beta is happening with regards to translations. That's probably
why you've got the weird code going on.

**Comment by goggi-** [comment]
Thanks a lot! I'm all happy now that I've got my ears back and know where the weird code is coming from. (:

**Comment by deilann** [comment]
Glad to hear it! :D

**Comment by elritch** [comment]
My issue seems to be related, I've died several times when I was sure I had done my dailies, thanks to this, I can't seem to make it past level six.  Two days ago I noticed I lost a ton of health but I was sure I did my dailies (and I'm not in any boss fight, only the egg finding task) so when I leveled up I made sure to check all of my dailies and didn't click any bad habits.  I made sure to refresh multiple times and make sure tasks were actually checked off.  Today I logged back on and while I'm not dead, I'm down 15 HP when I should have a full health bar.

**Comment by rwuni** [comment]
This just happened to me.  3 hours ago I tried to log in, and got an application error after hitting 'play' on the main page.  I tried a bunch of times, got the same result, decided the site was down, and went to the gym.

When I came back and logged in, I was glad to see my data come up, BUT I went directly from level 21 to level 16.  It seems like I died once for every time I tried to log in during the period of "Application Error."

I lost corresponding armor, gold, etc... but the system doesn't seem to have actually gone through six days (some of my streaks for dailies are still there), but it does seem to have started a new day (it shows dailies I clicked before "Application Error" as having been clicked yesterday, and thus having correct streak+1).

Further comparison pre-/post- "Application Error" shows that my tasks page went from 2 columns to 4 (site update?).

Honestly, I can just go add gold and level and buy everything back, but I bet that's not true for others-- this is kinda an unfortunate bug.

~Rwuni, Rwun on HRPG

**Comment by veghita** [comment]
This just happened to me... I just entered a new party yesterday and my actions have no effect on the quest, or at least don't show on the log. Today I unmarked the tasks I completed yesterday and checked them again to see if it was because I hadn't waited a full day, but no action on the quest again. Could it be somehow related?

**Comment by deilann** [comment]
If the quest started before you jointed the party, you're not part of the
quest.

**Comment by veghita** [comment]
Oh, then I just died. :( Thanks.

El 07/07/2014 02:21, deilann notifications@github.com escribió:
If the quest started before you jointed the party, you're not part of the
quest.

On Sun, Jul 6, 2014 at 5:10 PM, veghita notifications@github.com wrote:

> This just happened to me... I just entered a new party yesterday and my
> actions have no effect on the quest, or at least don't show on the log.
> Today I unmarked the tasks I completed yesterday and checked them again to
> see if it was because I hadn't waited a full day, but no action on the
> quest again. Could it be somehow related?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/2601#issuecomment-48131240.

---

**Comment by tessaracked** [comment]
I was level 20, using the Android app to update my dailies, and it told me I died twice.  When I checked my account in Chrome, I've been bumped down to level 17.  I had a perfect day and lost 26 hp from my party, but shouldn't have died even once from that.  Any help in restoring lost levels and/or explaining what happened would be appreciated.

-Tessa Racked

**Comment by deilann** [comment]
Can you do me a favor and refresh your party page? I often find that not
all the messages are displayed until a refresh... so it may be hiding that
you've actually taken more damage from your party.

**Comment by deilann** [comment]
As for restoring lost levels, you can do that yourself via Fix Character
Values under Settings > Site.

**Comment by Alys** [comment]
We still get application errors, but the code has changed a lot since this was first logged that the causes are probably different now, so I'm closing this issue. We have more recent ones to track the errors, e.g., https://github.com/HabitRPG/habitrpg/issues/6495
