### ISSUE TITLE
Order of tasks are shuffled

### ISSUE THREAD

**Issue by lunaire** [HabitRPG/habitica#318]
This has happened seemingly everytime the server crashes or I get disconnected (i.e. today for the upgrade). The order of daily and todos are shuffled in a seemingly random fashion. Quite annoying since I had them ordered in order of importance.

Also, now I cannot re-order the tasks; it gets reset to this current order after I refresh the page.

[Intel/ windows 7 system, chrome browser]

**Comment by lefnire** [comment]
Confirmed. Fixing

**Comment by StanLindsey** [comment]
I get this too, sadface.

**Comment by horusofoz** [comment]
Here too :(

**Comment by wc8** [comment]
Mine got rearranged up and is insisting on the new order of things. That is to say, after refresh, it reverts to the wrong order.

**Comment by lefnire** [comment]
I've found the issue, but I'm not sure how to fix it. Here's the backstory:

Derby uses [refLists](http://derbyjs.com/#references) to maintain order of object lists. So you have `user.tasks` stored willy-nilly, then you have `user.idLists.habits` which filters tasks by type (habit), and maintains sort order. Well, a while back people were just losing their tasks wholesale. Turns out they weren't losing anything from `user.tasks`, they were just losing `user.idLists.*`. My hack to that can be [found here](https://github.com/lefnire/habitrpg/blob/master/src/app/schema.coffee#L48), which looks at `user.tasks` and puts it back into the refLists if they went missing for some reason - it only happened to some people, not everyone. Now, however, it's happening to everyone. So every refresh causes the idLists to go missing, and this hack puts all the taks back into place - in the order tasks were added to the user object. In other words, this hack can no longer be employed and we need to find the root of corrupt `user.idLists.*`

I'm babbling in case devs (@SlappyBag) are listening :) And thinking out loud.

**Comment by StanLindsey** [comment]
As I mentioned on gTalk instead of having two objects; one the tasks themselves and one for the task lists. Could you put the an extra variable in the actual task itself with its position. Then it could be uploaded/downloaded as one whole object instead of two and if the tasks display you'd know that variable was coming down the pipes. Then you'd just need the JS to display them in the order of that variable?

**Comment by lefnire** [comment]
fixed 5ea0dfe713efabed95e4ea4dc51ddfa5fc02d674

**Comment by lefnire** [comment]
I was lucky enough to have read @SLaks' commit message for this just today, I never would have figured this one out on my own https://github.com/SLaks/racer/commit/87921075fd65e55ad1e283700a1962a3c8010983

**Comment by lefnire** [comment]
some people are still finding this to be an issue, re-opening

**Comment by ghost** [comment]
Happened to me just now...

**Comment by StanLindsey** [comment]
> _< I blame the date pickers.

**Comment by lefnire** [comment]
naw, we're reverted back to a commit before due-dates. It's actually been an issue for the last few days still. I blame refLists. Also, I'm keeping a keen eye on https://github.com/SLaks/racer - this guy's been fixing up refLists and model queries like woa

**Comment by StanLindsey** [comment]
I was making a funny =( 

Many projects seem to be having problems withth derby refLists if I recal

**Comment by SLaks** [comment]
If you can reproduce this, can you try to determine whether the IDs are wrong (in which case the problem would probably be in listenerQueryMutator or types/find.js) or whether the refList is broken?

**Comment by mattrozak** [comment]
i went to assign a due date on a todo.  As soon as I clicked on the date textbox, all habits, dailies, todos, and rewards vanished. After I refreshed, everything was still there but was shuffled.

Whenever my tasks do get shuffled, it's usually preceded by everything vanishing momentarily/until a refresh.

**Comment by kwilson328** [comment]
Haven't touched due dates yet, but experiencing the same event order as @mattrozak, vanishing -> refresh -> shuffling

Chrome v24.0.1312.57
OSX 10.7.5

**Comment by lefnire** [comment]
possible clue https://github.com/codeparty/racer-db-mongo/issues/6#issuecomment-13816218

@SLaks I'll give your suggestions a try moment I can, thanks!

**Comment by ericwilmoth** [comment]
very much looking forward to the solution...

**Comment by l--l** [comment]
Even if the order of tasks is not shuffled, most days I can't even drag and drop my tasks to arrange them in the order I want.  This function seems to be working only intermittently.  Any idea when this might be stable?

Chrome 25.0.1364.99
Mac OS 10.8.2

**Comment by horusofoz** [comment]
Today this is not happening for me. Can anyone else confirm if it appears resolved?

**Comment by horusofoz** [comment]
Closed in error.

**Comment by ghost** [comment]
It is still happening to me

**Comment by horusofoz** [comment]
@Neohuman Can you clear your browser cache, close, reopen and test again?

**Comment by ghost** [comment]
I did that and the problem still persists

**Comment by lefnire** [comment]
Nothings fixed here, i'll chime in when we have a fix. Looking into bounty
for fixing this

**Comment by horusofoz** [comment]
I experienced 14 hours today without my tasks being reshuffled after being able to order them without a hitch. Then tonight I accessed the app from my phone and after a glitch with select a habit plus and refreshing the page I saw a reshuffle had occurred. I can't think of why but the trigger in this instance appears to be accessing the app from my phone. Note: Android/Chrome.

EDIT: Returning to the web app I was having trouble dragging tasks. I closed all mobile instances, refreshed the page and voila, able to drag/order tasks. Refresh page and tasks retain order.

**Comment by ericwilmoth** [comment]
Glad to see this is one of the current items. Looking forward to being able to get back to RPG once this is fixed.

**Comment by horusofoz** [comment]
I tested on my phone again today and above behaviour did not repeat. Must have been a coincidence. Disregard.

**Comment by Pandoro** [comment]
For me the shuffling was caused by actively reordering and refreshing the site a lot of times in a row. Right now... I don't really feel like reproducing this ;) But it might be some hint on where to look for the bug when trying to reproduce it.

**Comment by horusofoz** [comment]
Thank @Pandoro. This could render my previous info relevant as I was
Constantly switching between my PC and mobile for the app. Sounds like the
contant refreshing could be a commonality at least between our own
instances.
_Horusofoz_
*
*
"Live to learn. Learn to live." J.W.S.

**Comment by lefnire** [comment]
for anyone that this is definitely a problem for still, shoot me your user id if you could

**Comment by ericwilmoth** [comment]
Does it matter if we publicly post them, or should it be a P.M?
I've been avoiding using RPG till there was a clear fix for this...so short of reordering things and seeing if it fails again i can only assume it's still a problem...unless there was an attempted fix I'm unaware of?

**Comment by lefnire** [comment]
email it to me directly: [link](mailto:tylerrenelle@gmail.com) (though, since api-tokens were enacted it _is_ safe to show UUIDs publicly)

**Comment by lefnire** [comment]
I haven't fixed anything directly, but I've been merging in SLaks' Racer fork commits periodically, many of which deal directly with refLists (refLists definitely being the issue with this ticket). So I check in here from time to time to see if any recent Racer fixes solved the problem..

**Comment by ericwilmoth** [comment]
Thanks--i just sent my id to you. Given your last comment, does that mean I should give it a shot and see what happens, or wait till you've had a chance to play with it further?

**Comment by ericwilmoth** [comment]
incidentally, i just tried moving a couple items, the page hiccuped...i refreshed, and the changes i made were discombobulated again, so it's definitely still happening.

**Comment by horusofoz** [comment]
If it helps, I'm not experiencing any shuffling issues or trouble reordering tasks, however I found I can move tasks around with out issue but still can't move rewards. Same behaviour as before where it selects text rather than move around the item.

**Comment by lefnire** [comment]
You can't move items, those aren't sortable. reward-rewards?

**Comment by Pandoro** [comment]
@lefnire, no I can confirm this, sometimes I can drag and drop custom
rewards, sometimes it will just select them. This seems to be related to
the duplicate reward bug though.

**Comment by lefnire** [comment]
Roger that, I'll work on rewards today then

**Comment by lunaire** [comment]
Just a few extra info: I'm the one that opened this issue, and this issue
is fixed for me. No more shuffling of tasks or rewards.

I am currently unable to move tasks/rewards manually on one of my
computers(it only selects the text when I click & drag), but I think this
is a separate issue.

**Comment by BenMilford** [comment]
Just to add to the mix, I've been able to order items without shuffling since yesterday.

**Comment by derekantrican** [comment]
While this is still open, I'd like to mention another bug. (It seemed better to post it here because this thread is mostly related and I didn't think it was necessary to open a new one. But if I should open a new thread, let me know).

Basically: I can't rearrange rewards.

**Comment by lefnire** [comment]
reward re-arrange should be fixed now (note you can't rearrange store items)

**Comment by horusofoz** [comment]
Confirmed now able to rearrange custom rewards

**Comment by ericwilmoth** [comment]
I've been back in the saddle for a few days now and everything seems to be staying sorted, so far as I can tell, it's fixed. Thanks!

**Comment by lefnire** [comment]
cross our fingers!

**Comment by Pandoro** [comment]
Hate to say it, but this just happened for me. Was refreshing as some of the stuff did not check correctly and after several refreshs, eventually everything got messed up :x 

It is not so critical, as it is a side case, but I think it is still a problem ;x

**Comment by lefnire** [comment]
we're exploring moving away from refLists, I'll chime in here if that happens

**Comment by SLaks** [comment]
Note that I'm in the middle of some very heavy performance work on refLists (see https://github.com/SLaks/racer/commits/refList-perf), which affects the behavior of nested refLists and may help here.

I'd like to take a look at this issue and see if I can figure out what's going on here, but I won't have any time for that for at least a week or two.

**Comment by lefnire** [comment]
@SLaks I don't think it's performance issues per se effecting this ticket. We're experiencing some hard-to-explain funky-ness with `refLists` in other areas of the app too. Eg, we're trying to add categories ([see commit](https://github.com/toebu/habitrpg/commit/592486384900c4c7e422e949e4b85e10a702cd85)), and adding new items to the refList bugs out which task has the category assigned to it - seems the `:task.id` reference gets shifted. It could be we're not using them properly, or bugs in our own app - but we're thinking of just moving our refLists to arrays instead. @toebu knows more some of the refList issues.

I see you've been just strong-arming the Racer codebase though, I'm a huge fan of your fork!

**Comment by SLaks** [comment]
I realize that performance is not what you're looking for, but I'm reworking enough of the code that it might help.

Two particular weaknesses in the current Racer code that I've noticed but am not working on right now is handling changes to parent paths (see my recent Racer issues) and translating paths when performing set operations on refLists (which may be causing some of your issues)

**Comment by lefnire** [comment]
Here's a description of above issue: https://github.com/lefnire/habitrpg/issues/634 - totally don't meant to rope you into our troubles, I know you've got a lot of unroll.me on your plate :) But it could provide some handy info anyway.

Actually, that last bit sounds exactly like the issue - translating paths when performing set operations.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks! Anyway sorting has still to be ported to new site
