### ISSUE TITLE
Re-Roll hover description flickers rapidly

### ISSUE THREAD

**Issue by Olathe** [HabitRPG/habitica#399]
On Chrome stable, the `Re-Roll` reward hover description flickers rapidly. When I watch the timeline on Chrome's developer tools, I see `mouseOver`, `mouseOut`, `webkitTransitionEnd` cycling rapidly.

Ger Hobbelt [solved a problem that sounds quite similar](https://groups.google.com/d/msg/d3-js/ieQYPqHmLHo/Lw2_hO1SZysJ):

> The solution was to detect whether a mouseout is due to the user now hovering over the tooltip div or not and in case he/she is, further postpone the tip.erase action until the user actually leaves the tooltip area.

I'm not sure if that's the actual problem, but I do notice that the `Re-Roll` description tooltip is the only description tooltip that covers the pixel my mouse is pointing at.

**Comment by Olathe** [comment]
Unlike the other reward description tooltips, the `Re-Roll` one's pointy part is _above_ rather than _to the left of_ the icon you hover over. This brings it too close to the mouse cursor a good part of the time. So, if you hover over the bottom right part of the icon, the tooltip appears fine. If you hover over the top left, it flickers.

The same problem occurs with the popup messages that tell you what the pencil and trash can do on other tasks. They are too close, so if you put the mouse cursor toward the top of the icons, the tooltips that appear flicker as well.

**Comment by wc8** [comment]
I see a flicker if I don't get the mouse in the just the "right" place. 
If I get it over the sweet spot, there's a display issue: the tooltip (which is a display of the reward's note) is caught within the frame and it doesn't fit. 
There are no issues with any other reward descriptions.

**Comment by wc8** [comment]
Correction: I don't encounter any issues with the other tooltips, I don't mean to discount what you're experiencing.

**Comment by Olathe** [comment]
Yeah, that's the same for me as far as the other reward descriptions (they seem to work alright), though it does happen if you hover over the task mini-icons.

For example, hover over a task and then hover over the pencil icon. Up will pop a black speech bubble that says `Edit`. If you inch the mouse up to the top of the pencil icon, your mouse cursor will be positioned on a pixel contained within both the pencil icon and the speech bubble.

Because the speech bubble is currently occluding the pencil icon, you're no longer technically hovering over the pencil icon, so the speech bubble disappears; then you're suddenly hovering over the pencil icon, so the speech bubble reappears; then it cycles rapidly through the two states.

**Comment by Pandoro** [comment]
While trying to replicate I noticed that I can see 1 tooltip, regardless of which one and then I cannot see any other tooltips until I refresh the site. The re-roll one somehow doesn't appear at all though, however it does make a sroll-bar appear on the reward list for a very short time. 

So this still seems to be an issue.

**Comment by rixx** [comment]
Now it's different (for me, at least, Firefox/Arch Linux), but the tooltip still behaves differently. Sometimes it doesn't appear, then flickers if you hit the right spot.

**Comment by lefnire** [comment]
actually should be fixed as of https://github.com/lefnire/habitrpg/pull/757, @rixx is that the case for all rewards?

**Comment by rixx** [comment]
Nope, just the re-roll one. 

(BTW, I hope it's ok that I go through old tickets and comment on the ones that should or could be closed. If not: just say a word.)

**Comment by lefnire** [comment]
you're doing great :) i'll just wait a bit to hear back from the ticket owners & close otherwise, thanks for the help

**Comment by kalmduck** [comment]
I was testing this out today on Chrome, and I still see some flicker.  At first I thought it was just related to the Re-Roll tooltip, but I explored it some more.  I added a lengthy note to a to-do (one that would take the tooltip to it's max-width) and had similar issues.

This is dependent on the browser window size, though.  If I make my browser window full-screen on a 20-inch display, it is fairly difficult to replicate, but if I make the browser window as narrow as it can be and still have the 4-column layout, I can get a flicker on most of the notes that I have.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by kalmduck** [comment]
I did a quick check, and this issue still persists.  I don't use details comments much on my habits, but I still notice it with the Re-Roll option.  If the browser window is sized fairly small (but still displaying in the site in 4 columns), it is near impossible to get the details hover for Re-Roll to display.  If it does display, it usually doesn't stick around for long.

As far as I can tell, this behavior has not changed.

**Comment by SabreCat** [comment]
Dah! I thought I'd reopened this ages ago. Doing so now, per @kalmduck's and @wc8's recent comments and my own experience.

**Comment by SabreCat** [comment]
Assigning to myself because I've been doofing around with popovers quite a bit lately and will take a stab at it. But if somebody more savvy spots the fix first, don't let the assignment dissuade you :P

**Comment by wc8** [comment]
Right now it’s kind of a roulette. 
Sometimes I get the yellow label ![yellow label hover](https://f.cloud.github.com/assets/3326182/1674739/ae839404-5cfd-11e3-97cd-5d8d52185c1b.png).
Sometimes I get the white speech bubble style (the ideal) ![cake hover](https://f.cloud.github.com/assets/3326182/1674749/d2f02ec4-5cfd-11e3-953d-271b06f7f5eb.png)

Sometimes I get nothing—or nothing until the cursor is over the right spot. If I’m still moving the mouse, there’s the “flicker” effect.
Sometimes one has to leave the cursor in the the general area and, if it’s the sweet spot, the notes appear.
Sometimes it’s easy. Sometimes it’s impossible, even resizing the browser.

Because of this I rarely use notes and am suggesting [this](https://trello.com/c/x7Zm7UCY).
(It took me a quite a number of tries to get those pictures.)

**Comment by lefnire** [comment]
This will be quite difficult to fix ourselves, we're using angular-ui-bootstrap for popovers. We'll probably want to revisit this ticket after we've upgraded ui-bootstrap (we're very far behind on that lib, but our app is so tied to an older version that upgrading is a large task). It might _just fix_ the issue once we've upgraded, we'l see

**Comment by lefnire** [comment]
Actually, forgot I had thought this would have been fixed before (as per @SabreCat's comment https://github.com/HabitRPG/habitrpg/issues/1328#issuecomment-29676349). Yeah, maybe it's something we're doing with CSS / positioning then that's conflicting. Not sure

**Comment by snicker** [comment]
Angular-bootstrap currently has issues with html popovers with Angular 1.2 because of the way HTML safety is handled and the strict contextual escaping stuff

**Comment by brightbold** [comment]
For me, the popovers work perfectly in Chrome (Mac) but in Firefox and Safari they are so persnickety that they just flicker. It's practically impossible to find the right place to put the mouse to get them to stay open so you can read them. I noticed this when trying to figure out what the new spells did (and eventually resorted to using Firebug to read the markup!) I thought this was a new problem introduced with the classes rebuild, but I guess I've just never really needed the popover notes until spells were introduced.

**Comment by CSLH** [comment]
This same problem is occurring for me with the popovers on the rewards items. Rarely does on actually pop up, maybe 5% of the time I try.

**Comment by SabreCat** [comment]
The fix I came up with for this is live. We can reopen if people don't like this solution.
