### ISSUE TITLE
The quest owner has left the party

### ISSUE THREAD

**Issue by BlueberryGirl** [HabitRPG/habitica#4181]
I could not get my party details to refresh in either Chrome or IE so went to the app on my iPhone.  On my iPhone there is the message "The quest owner has left the party. <etc. etc.>"
I did not intentionally leave the party, however, have had issues with party data refreshing and wonder if I clicked too many buttons while in Chrome.
Please would you re-join me to my party and our current quest and have my damage from my last Chron roll-over applied to the quest?
My user id:  443c43e3-7979-4c3a-8fc3-ef521c5e1d84
Currently both Chrome and IE show that I am in the party and in the quest, however, neither shows the damage I should have done to the boss last night during Chron that gets recorded first thing when you log in on a new day.
Only my iPhone app says "the quest owner has left the party".
Please let me know if there is any other information you need or how I can help.
Thank you, 
BlueberryGirl
##

**Comment by Alys** [comment]
This was reported in https://github.com/HabitRPG/habitrpg/issues/4074 and has been fixed although the fix has not yet been ported to the mobile apps.

Regarding the missing damage, on your party page on the website, have you clicked the sync button (the one that is right next to "send chat")? That will make new messages appear in the part chat. Can you see your damage now?

BTW, chron is actually spelt cron (no h). That will be important if you ever need to search the wiki for information about cron.

**Comment by BlueberryGirl** [comment]
Alys, thank you for the very quick response
Yes, I have clicked the party sync button and I see:
 - expected messages from a day ago and before
 - damage a party member had applied 3 hours ago
 - Tools of the Trade I cast an hour ago
However, I still do not see damage from my character that should have been applied over an hour but sometime today.

**Comment by Alys** [comment]
Your public API data reports that you have 68 points of damage built up, waiting to be applied to the quest boss. I'm guessing that might be the damage you obtained yesterday as well as so far today - does the number sound about right for that to be true? If so, it will almost certainly be applied to the quest on the next time your cron runs. There is a bug that occasionally prevents the damage being applied on one day (https://github.com/HabitRPG/habitrpg/issues/2613).

**Comment by Alys** [comment]
I'm closing this because it's no longer possible to deliberately leave a party when you are the quest owner, and if this happened through a bug, we've received no other reports of it.
