### ISSUE TITLE
Mustaine's Milestone Mashing Morningstar not appearing

### ISSUE THREAD

**Issue by HSalgo** [HabitRPG/habitica#4249]
Hey there. I'm surprised no one else has had this problem, but I just finished the "Iron Knight" quest, and the "Mustaine's Milestone Mashing Morningstar" has not appeared in my inventory. I used the new data fetching option to look into my inventory, and it says that there is a shield there with the name "String 'weaponSpecialGoldenknightText' not found." and with incorrect stats +25 CON, +25 PER. I'm not sure if a change was made that caused this to sort of explode, but I figured I'd bring it up to your attention.

Cheers!

**Comment by lefnire** [comment]
That's the correct item (it's a "shield" as in, an offhand item). Those are the off-hand versions of the weapon's stats. It show up on your avatar if you click it? I'll fix the translation part

**Comment by HSalgo** [comment]
I don't see it in my inventory at all. The wiki (http://habitrpg.wikia.com/wiki/Mustaine%27s_Milestone_Mashing_Morningstar) says that the stats should be +17 STR, + 17 INT, +17 CON, so I was surprised to see the +25 CON, +25 PER there. Regardless, I don't seem to see it anywhere at all--it isn't selectable. Perhaps it has something to do with the error in the name?

**Comment by lefnire** [comment]
fixed in https://github.com/HabitRPG/habitrpg-shared/commit/d74f9d7a47c1829869c1b1bc7592ee09cacae5a2, will push later. In the meantime, if you click on the tiny box which gives you that hover-over, it'll equip the item (the actual item is defined properly in code and will show on your avatar)

**Comment by HSalgo** [comment]
Got it, thanks! I'll report if things are still wonky after the push.

**Comment by taldin** [comment]
Hang on a sec... according to the code and tested on my local install, you get _two_ artifacts -- 1) Jean Chalard's Noble Tunic, which is the same reward from finishing Necro-Vice  2) a DIFFERENT version of Mustelaine's Mashing Morningstar offhand, which is +25 Con/Perception, as opposed to the +17 all main hand that Kickstarter contributors got.... is that right?  (see pic below with two morningstars with the same name, but different stats and different hands).
![image](https://cloud.githubusercontent.com/assets/9312226/5081090/01d26958-6e7f-11e4-8867-b6401f4cb02e.png)

**Comment by HSalgo** [comment]
Oh, hm, taldin's right. I didn't even notice, but the quest DOES say that you gain Jean Chalard's Noble Tunic again. I'd already gotten it previously, so I didn't realize that it'd dropped again.

I wasn't involved in the Kickstarter, so I don't have the main-hand MMM (+17 STR/CON/INT).

My off-hand MMM (+25 CON/INT) still does not appear properly on my Equipment list. Only by blind mousing in the spot where it SHOULD be do I see a tiny box that has the title text, "String 'weaponSpecialGoldenknightNotes' not found." followed by the descriptor, "String 'weaponSpecialGoldenknightText' not found." Maybe it'll get fixed at cron? It's still an issue now though.

**Comment by HSalgo** [comment]
From Inventory - Equipment page:
![habitrpg - off-hand mmm glitch](https://cloud.githubusercontent.com/assets/8142937/5083283/24d14946-6ec1-11e4-9bc4-9941fe75f76e.png)

From HabitRPG Official User Data Display - Equipment Recommendations page:
![habitrpg - off-hand mmm glitch - fetched equipment data](https://cloud.githubusercontent.com/assets/8142937/5083285/2a9b1ece-6ec1-11e4-9d2d-dcccd0577926.png)

**Comment by lefnire** [comment]
Part 1 solved here
https://github.com/HabitRPG/habitrpg-shared/commit/619c8f6f17557ec9deff659f808d4ba5c463a222.
The diff stats is correct, the offhand has different stats than the main
hand version. Re: "string not found", the translation fix hasn't been
deployed. Eta 24h

**Comment by taldin** [comment]
All right.  So we have two versions of MMM, the publicly available OH and the backer MH, which is unavailable to mortals.    That's going to be a bit tricksy to explain on the Wiki (and demonstrates why early datamining is not always a good thing. :)  )

**Comment by HSalgo** [comment]
Duplicate naming! Ahhhhhh!

**Comment by taldin** [comment]
Yeah, hence my question.   I'm thinking that if only Kickstarter Backers can get the MH version, to just rename the OH "Mustelaine's Minor Mashing Mace" perhaps or something like that, to make them similar but different if you wield both of them. :)

**Comment by lefnire** [comment]
@lemonesstree

**Comment by lefnire** [comment]
Sorry, @lemoness I mean

**Comment by lemoness** [comment]
SO the reason we made them different is because that was the only legendary
item that didn't fit the +25 +25 stat model, and having it in the right
hand meant that it could not be equipped at the same time as Stephen
Weber's Shaft of the Dragon. When you run the numbers, it's pretty obvious
why we made this choice:

Stat bonuses from equipping maximum number of legendary items:

Old version 1 (MMM)
+42 STR
+0 PER
+42 CON
+67 INT

OR

Old version 2 (SWSotD)
+50 STR
+25 PER
+25 CON
+50 INT

## 

New version
+50 STR
+50 PER
+50 CON
+50 INT

Now you can equip all four legendary items for +50 to each stat, instead of
having INT be heavily favored in both versions with PER deeply ignored.
We're keeping the original weapon because the Kickstarter backer did want
those unbalanced stats for his own weapon when he requested it, but for the
new version (which should be listed as the mainstream one on the wiki, as
it's the one that can be earned by our players), it made way more sense to
keep the game balanced for everybody.

I'm not convinced it needs a name change - think of it like the rogue
weapons - but if we are going to alter one, we could name the Kickstarter
one Mustaine's Major Milestone Mashing Morningstar so that the one that
goes out to all the users still has the name that he intended. My personal
inclination is to leave the names the same, but I can be out-voted on this.

**Comment by Alys** [comment]
I think leaving them both with the same name is not going to cause too much confusion because so few people will have the Kickstarter (KS) version. On the wiki, we could refer to the quest version everywhere and never mention the KS version, with the only exception being a note at the bottom of the [MMMM](http://habitrpg.wikia.com/wiki/Mustaine%27s_Milestone_Mashing_Morningstar) page to explain that the KS backers have a different version. I'm pretty sure this would cover all the required information well enough, without much bewilderment. Taldin, what do you think?

**Comment by taldin** [comment]
The way I understood it was that the KS backers got the items before anyone else did, but as time has gone on the items have become available to questers.   At the time it made logical sense to me that the KS MMM (+17 Str/Int/Con) was a main hand available as an alternative to SWSotD (+25 Str/Per) such that your class choice predicated which one you were using (Healers would pick the MMM, Rogues and Warriors SWSotD, and Mages... well, their staff is still better); I had a discussion with someone staff-like in the Tavern commenting about how SWSotD was somewhat useless for a Mage and he said 'wait for other artifacts to come out'.)   The KS MMM has been in the codebase for a long time, and Thepeopleseason put up the page with it as 17/17/17 back in April from datamining even though the quest hadn't been released yet.    

The new version of the MMM from the quest (QMMM? :) ) does indeed provide symmetry for stats, and fits in the one equipment slot that didn't have a legendary, but it seemed a little shoehorned into place as a 'shield' when it's not a shield but a weapon (I know, I know, Rogues) and the main hand KS MMM has been 'out there predicted' for so long.

However.  :)  You are the content maven, and it is what you say it shall be, so I'll take care of the necessary Wiki fixes.  (Probably can't hurt to put a Trivia section in about why some lucky people have two.)

Thank you for the insight!

**Comment by HSalgo** [comment]
I'm a nobody, but I'm big on clarity, so I think having some differential would be good, but other than finding bugs and reporting them once in a while, I really have no effect!

**Comment by HSalgo** [comment]
The name fix went through, and I can see the item properly! Thanks again!
