### ISSUE TITLE
Cannot feed my pets

### ISSUE THREAD

**Issue by Pascalelevac** [HabitRPG/habitica#4749]
When I give the food to the pets there is a message to report the bug here.  The food disapear like if my pet was fed, but the green bar didn't move, like he was not fed.  I lost 4 different food, in trying, I reload the page, but it doesn't work better, and the error message was still there.

API: ce8550fb-8b5f-430c-945f-17f90fc7e12b

**Comment by crookedneighbor** [comment]
I believe this is due to a [combination of this commit](https://github.com/HabitRPG/habitrpg/commit/5aa401524934e6d9071f13cb2ccca0dba13cdcff) and the strings for non-English languages not being updated to use the new key, pet. 

I'm going to revert the key to use egg, and deploy that should fix it for now. It's not semantically correct, but since it's blocking you from feeding the pet, that's what we'll do as a stop gap.

**Comment by deilann** [comment]
No, Blade, the pets are being fed. Just checked the user object.

This is probably due to the user using Internet Explorer.

**Comment by crookedneighbor** [comment]
I'm still going to revert back to egg as the key, in order to prevent additional people reporting it (since they're instructed to report it when they see it). [Commit here](https://github.com/HabitRPG/habitrpg/commit/016e359690cd7a51f9a0a1ba27fa54f7d81bff68)

**Comment by deilann** [comment]
No worries. But it won't fix this... just get rid of the error message. Pet
bar will still not fill up, as long as someone is using IE. That being
said, it's just a display issue and pets are being fed properly.

**Comment by crookedneighbor** [comment]
Going to let issue #3218 be used to keep track of the IE feed bar issue.

**Comment by deilann** [comment]
Yah def, just don't want the user confused.

**Comment by Pascalelevac** [comment]
Just to tell you that I’m not using internet explorer I am with Mozilla firefox

**Comment by deilann** [comment]
Can you show a screenshot of your pets page? I most certainly can see that
your pets are growing in your user object.

**Comment by Pascalelevac** [comment]
I don’t know why but today it’s working,  yesterday I lost 4 food ...

**Comment by crookedneighbor** [comment]
@Pascalelevac Any way you can be sure that the food was lost, and not that the progress bars just weren't updating until a refresh?

**Comment by Pascalelevac** [comment]
yes, I am really sure that the food was lost.  I did a refresh and nothing change on the progress bars. I fed the same pet with 4 different food, usually I can see the progress with one food, and that time I cannot, even after 4!

**Comment by deilann** [comment]
mmm, do keep in mind that if the food isn't "preferred" it adds very little
to the bar -- so little that it might not be noticeable. If you did 4
different foods, they probably weren't all preferred.

**Comment by Pascalelevac** [comment]
I know, but I just give 2 food, to the same pet, not its preferred too, and I saw the bar progreesed

**Comment by Lebriz** [comment]
Same here, I get that it could be IE related but until I go see it from another browser I will not be assured that they are fed. I mean, I spent a BUNCH of strawberries on my lion and was wishing he would grop up finally.

**Comment by Lebriz** [comment]
Also, stop with the "maybe it isn't preffered!!11", we are all capable of seeing if ANY progress is made, let alone the preferred food secret is the easiest riddle to solve on earth. 
And it is no excuse for developers to just ignore such issue, I mean, isn't fixing whatever problem on whatever platform the point here or are we governed by Non-IE Supremacists?
