### ISSUE TITLE
Missing Pets and Potions After Using Key to the Kennels

### ISSUE THREAD

**Issue by kitten22** [HabitRPG/habitica#4777]
I released all my pets and mounts yesterday and then rehatched over twenty pets. Since then half the newly hatched pets have disappeared as have most of my hatching potions even though I didn't use them. There is something seriously wrong here. They were hatched using Chrome. User id 72255804-870f-44aa-bd24-91c295552f93. Thanks.

**Comment by Alys** [comment]
I have looked at the code for Key to the Kennels and there is no possible way that it could have caused this. The Key takes effect immediately upon purchase and then has no lasting effects. Any pets and potions that disappeared more than a few seconds after the Key had been purchased had to have been removed by something else.

I suspect it's a [sync error](http://habitrpg.wikia.com/wiki/Sync_Errors) or an example of the "two versions" bug https://github.com/HabitRPG/habitrpg/issues/4313. @kitten22 what this means is that the actions you took in your browser to rehatch the pets were not properly synced to HabitRPG's server and so when syncing did happen later, a lot of your actions were lost (i.e., pets that looked like you had them then disappeared). When you rehatched over twenty pets, did you do it all at once, very rapidly? That can increase the chance of a sync error so I'd like to know if that's what happened. 

However that doesn't explain potions that you hadn't used going missing. I'm going to download a database backup so that I can see exactly what you had before you rehatched the pets so that I can investigate further.

Can you please tell me the date and time and timezone when you used Key to the Kennels? It's okay to be approximate of course - if you can remember to the nearest couple of hours that would be fine, or even give a time range over a few hours for when you used it. For the timezone, please tell me it in numerical format (e.g., GMT-3) rather than using a local abbreviation.

**Comment by kitten22** [comment]
Hi!  Thanks for getting back to me.

I did hatch my pets one after the other and it looks like only the last 12
actually went through and stayed.

I think I used the key last night maybe around 10PM GMT-5.

So you think this may be part of the ongoing problem with using the Chrome
browser and the constant errors?  Should I start using a different browser
or something?

At this point it doesn’t really matter since I’ll eventually re-earn the
pet eggs and potions, but it’s just disappointing.

Thanks.

**Comment by Alys** [comment]
@kitten22 Thanks for that time! That helps me work out which backup to look at.

The ongoing sync/caching problems aren't specific to the Chrome browser and I don't recommend switching to a different one. You'll probably see more reports of people having problems in Chrome, but that will be because more people use it for HabitRPG. We recommend Chrome because it has the best support for our features and because it gives the best error messages when problems occur. 

I understand completely your disappointment! Twice now I've used the Key and rehatched a lot of pets immediately and I would have felt gutted to see them all disappear. I can definitely give you back all the pets you lost, or at least the eggs and potions so that you can rehatch them again. Sorry - I should have mentioned that earlier! I just took it as assumed that I'd give them back to you because we always do that, so I didn't bother mentioning it, and I now realise that was an unhelpful assumption. :)

**Comment by kitten22** [comment]
Hi!

One of my party mates just brought to my attention that my stats are saying
that I released my pets and mounts and got Triad Bingo twice so that may be
the glitch.  I guess it released everybody a second time!  So you must be
right that it was the syncing issue.  Whoops!  I guess I was just a little
too overzealous with my pet hatching.  :)  I’m very jealous that you’ve
already used the key twice!  I’m definitely looking forward to my second
Triad Bingo!  :)

Aw!  You don’t have to do that!  I do appreciate the offer though!

Thanks!

**Comment by Alys** [comment]
@kitten22 Are you missing any gems? If so, how many?

Thanks for your information about your stats. That's given me a much better picture of what happened. More details soon!

I will definitely give you back your lost potions and eggs; this is not up for debate. ;)

**Comment by kitten22** [comment]
Hi!

Um, I don't think I'm missing any gems.  I bought a few quest scrolls in
February (yea Rocks!) plus the Key so 30 seems about right.

I really appreciate you keeping me updated!

Thanks!

**Comment by Alys** [comment]
@kitten22 I've given you back the eggs and potions that you had shortly before you used the Key to the Kennels. This means that you should be able to re-hatch the pets that you lost. If I've missed any, let me know! Also tell me if you have any more problems with the pets staying after you've hatched them.

I still can't see anything wrong with the Key to the Kennels itself and I'm attributing the problem to sync/caching errors. We've been having a few of those lately and they can have the effect of undoing actions that you took or duplicating actions.

**Comment by kitten22** [comment]
Thanks so much!  I really appreciate it!

I'll make sure to keep an eye on the little blue line and make sure it
completely disappears before I go hatching another pet (or anything else).

Thanks again!
