### ISSUE TITLE
errors in translatable locales text for Tour (Was: Closing tag missing in npc.json)

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#4885]
While trying to translate new strings to French, I received a warning from Transifex about a missing closing `</li>` tag on string 40 of npc.json. But as far as I see it, the closing tag is also missing from the source string.
![screenshot - 19032015 - 14 34 28](https://cloud.githubusercontent.com/assets/4882150/6731593/208e3116-ce46-11e4-8043-bb3e3a5f0c52.png)
If this is a mistake, then the correction will be fairly easy. But if this is intended, I fear other translators might add this missing tag to cancel the warning.

**Comment by Alys** [comment]
@Blablux thank you! It's very kind of you to take the time to report this. I believe it is a mistake and I'm looking into that now.

**Comment by Alys** [comment]
Fixed here: https://github.com/HabitRPG/habitrpg/commit/c880c525b479922acaa01526e2158cc8426cc02e

@Blablux I've added the closing li and ul tags to the source string. The change might not appear in Transifex for a while. Until then, it's up to you whether you add the </li> and </ul> or not. The site will run correctly either with or without them, so whatever is easiest for you. Thanks again!

**Comment by ghost** [comment]
As I'm still translating, I'll add those in Transifex right now, so that no additonnal work would be required when updated. Thanks for the fast response and correction.

**Comment by Alys** [comment]
Great idea!. Note that I removed some excess `<b> and </b>` tags too, if you haven't already seen that. Thanks!

**Comment by ghost** [comment]
I corrected all of that, but strangely, Transifex now throws me a warning : `The translation added a new tag: 'ul'.`
I triple-checked to see if I did any mistake, but I only see one `<ul>` and one `</ul>` properly nested. If I remove the `</ul>`, I don't get anymore warning.
Still, I saved the translation with a `</ul>` as it seems the proper thing to do. I just hope reviewers won't slap me for not sticking to the actual source string's code.

**Comment by ghost** [comment]
@Alys I missed that when looking at your commit, but it seems that you forgot a `</b>` in the `Sample Good Habit`. Should do a pull request for that kind of mistakes ? (sorry, I haven't yet read the guidelines for contributing code, so I'm still guessing the best way to do things).

**Comment by Alys** [comment]
Yes, I definitely deleted that closing b tag by accident - sorry about that. However our chief programmer has been improving the tour over the past few hours, and the strings have changed dramatically. They are now in defaultTasks.json rather than npc.json. If you're not seeing that change yet on Transifex, it might be best to pause before doing more translations. Here's the file if you want an advance look at it: https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/defaultTasks.json

**Comment by ghost** [comment]
Thank you for the information. I can (and will) get prepared for the next transifex update with that.

**Comment by paglias** [comment]
Transifex should be updated now, let me know if it isnt

**Comment by ghost** [comment]
Hi everyone. Transifex has been updated, and I started translating. I noticed once again what seems to be a typo. Should I open a new issue in Github ? Should I continue to inform you in this one ? Or is there another way to report trivial stuff like that ?
This one is fairly minor. In defaultTasks.json, string 2 is `Sample Good Habits: + Eat a vegetable +15 minutes productive work`. As far as I see it, there should be a space between the second `+` and `15`. Transifex throws me a warning when I add this space, stating that `The translation does not contain the number "+15". Please avoid writing it in full.`

**Comment by Alys** [comment]
Thanks @Blablux! Let's keep it here for simplicity. I've renamed this issue from "Closing tag missing in npc.json" to "errors in translatable locales text for Tour (Was: Closing tag missing in npc.json)"

@lemoness Please see the comment just above this one (you can ignore the rest). Is this worth changing? Or is there another rewrite coming for the tour?

**Comment by ghost** [comment]
Then I might add, for the sake of consistency, that in the `Sample Good Habits` and `Sample Bad Habits`, sample habits are separated by a space. But in the `Sample Good or Bad Habits`, habits are separated by a `;`. This is not a mistake in itself, but I'm what you would call a grammar nazi and it forcefuly triggers a warning in my brain :)

**Comment by deilann** [comment]
I'm not saying this as a moderator, but just as a person... The nazis tried
to eradicate my family and tore us apart, to the point that we still have
missing branches of the family we'll likely never know what happened to.
Having that compared to being critical about grammar really hurts. There
are a lot of ways to express the sentiment. Do you think you can try
another next time? :/

**Comment by ghost** [comment]
You are right. I was saying that as a general expression, but this is not an excuse. Please accept my apologies for that. I'll do my best to choose wiser words next time.

**Comment by deilann** [comment]
Thank you so much. <3

**Comment by ghost** [comment]
Still hunting Transifex. In gears.json, I found that strings 110 and 429 both are `Exploding Squeak`, as are strings 111 and 430 for its bubble text. I searched if there was other duplicates for other Spring 2015 items but couldn't find another one (yet).
Update : I was wondering if this could be an intended duplicate, but as Transifex let us translate both strings differently, I'm pretty sure it wasn't intended, at least not that way.

**Comment by Alys** [comment]
That's normal. It's because the Rogue's shield is the same as the weapon, except held in a different hand. The shield and weapon descriptions are always paired. It's redundant in the locale files but makes the code much simpler.

**Comment by ghost** [comment]
I didn't see that one coming, but it's logical. Sorry for bothering you with questions that every new translator might have already asked. I'm updating my translator cheatsheet with every new details I learn about :)
I added a comment in transifex, so that people know that the translation might be used elsewhere... and corrected the french translations, that were indeed different for each item.

**Comment by Alys** [comment]
No worries! We don't actually get that question often, which probably explains why some of the translations were different when they should have been the same. :-/  Thanks for fixing them and adding the comment!

Your cheatsheet sounds useful! If you'd like to share what you're learning, I'm sure it would make a good addition to the [Guidance for Linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) page.

**Comment by ghost** [comment]
There is not much yet in my cheatsheet, but I have few ideas to expand it, and then I'll ask the Wizards of the Wiki if they find it useful and what's the best way to follow to add it to the wiki.

**Comment by ghost** [comment]
I was about to say that there is nothing wrong with the Tour translations anymore (and that this issue may be closed), but I just found a new translation issue while changing class. Just when changing class, you're brought to the equipment page, which shows a pop-up talking about class equipment:
![capture d ecran_2015-04-26_12-46-27](https://cloud.githubusercontent.com/assets/4882150/7336950/c77e897a-ec15-11e4-830a-98e65ba0ee74.png)
The _Finish tour_, _Prev._ and _Next_ are untranslated. I searched through Transifex to see if I could find these strings, but didn't find them.

**Comment by SpenserJ** [comment]
Scanning through old tickets for the Aspiring Coders Guild challenge, and this can be closed.

**Comment by ghost** [comment]
Just for the record: the last comment in the ticket hadn't been addressed, but I've linked it from the repository of untranslated parts of the site

**Comment by damemi** [comment]
I'd like to contribute to this, looking through the code I can find the Tour translation code in website/public/js/services/guideServices.js, but I'm not sure how to simulate this changing class/equipment issue (I'm new to Habitica). Could you possibly help me?

edit: to be more clear, I'm not sure how to use Habitica to get to the point where I can change my class/equipment

**Comment by SabreCat** [comment]
@damemi: Classes unlock when you reach level 10. A popup appears at that point, and choosing a class there takes you to the tour piece screenshotted above.
