### ISSUE TITLE
help text on tasks page should be translatable

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#5202]
On the Tasks page, the new question mark help icons show text that isn't translatable.

The text should be placed into `common/locales/en/tasks.json` (unless anyone has a different preferred location) and `website/views/shared/tasks/lists.jade` should be edited to use the translatable strings.

For those strings that contain wiki links, the links should be part of the translatable strings so that translators can insert links to non-English wiki pages, if they exist.

This would be a good job for a new programmer and I have advertised it in the Aspiring Coders guild.

If you work on this and find that you need assistance, you can ask by commenting in this issue. In your pull request, please include screenshots showing the help messages for the four columns, using the new translatable strings.

**Comment by hairlessbear** [comment]
@Alys In #5206, I noticed that the "Error processing string. Please report to http://github.com/HabitRPG/habitrpg" string is always in English. Shouldn't that be translatable too? If so, [this file](https://github.com/HabitRPG/habitrpg/blob/695b00b6bbfed61753026279b9e3e3f9dd32f105/common/script/i18n.coffee) is where it's located.

**Comment by GitHubSphinx** [comment]
@hairlessbear I believe that this ticket is devoted to a particular feature translation. There is also a general ticket for untranslated strings: https://github.com/HabitRPG/habitrpg/issues/4522

@Alys please correct me if I don't get it right

**Comment by ghost** [comment]
If no one else is handling this at the moment, I'll try to see into this issue in about half an hour and in two hours I hope I may have at least something done.

**Comment by ghost** [comment]
Ok, it seems that I'm ready with the changes in question.

The screenshot: http://i.snag.gy/gSpZP.jpg
You can tell that the lines are changed by the underscores which end the first line in each column. And of course they won't be included in the commit - the final screenshot: http://i.snag.gy/flikR.jpg

The only question left is if I should make all lines html-ready with (!) or only the current html-dependent lines. As far as I can tell from community guidelines, for example, translators avoid making all lines html-rendered with (!) - just in case.

However in this particular case I'm in doubt because the help text may be a subject to change in the near future - e.g. adding more links to wikia or making more words bold. That's why I'd rather preferred making all these lines html-ready.

What do you think @Alys @crookedneighbor ?

**Comment by ghost** [comment]
Ok, it may be better to leave the things in accordance with the previous practices, so I'm making a pull request with html allowed only where needed currently. 

@Alys @crookedneighbor Please excuse me, but I might have placed the merge request wrong... Should I correct the way it's been done?
Update: Below I've tried to correct my mistake with the target repository

@hairlessbear I haven't addressed your comment. So if this ticket gets closed you may want to report your issue in https://github.com/HabitRPG/habitrpg/issues/4522

**Comment by SabreCat** [comment]
This is duplicate effort of https://github.com/SabreCat/habitrpg/commit/3b607136337e919d4fa121e2df5d29f5f794506e, which we're currently doing some beta testing of.

**Comment by ghost** [comment]
@SabreCat thank you for your comment! I believed I saw this text partially translated live yesterday! But then it disappeared and I was too confused to believe myself.

Is it possible to make wikia links changeable in your commits? So that translators on Transifex could change links to the wiki pages in their language?

**Comment by crookedneighbor** [comment]
@GitHubSphinx Does transifex allow you to post different links? I know it throws a warning when the link doesn't match exactly, but I'm unsure if it allows you to save it or not despite the warning.

**Comment by ghost** [comment]
@crookedneighbor Oh, thank you so much for this reminder! As a reviewer I have almost forgotten about the cases when Transifex gives a warning. And I haven't even mentioned it when discussing the question in the [Wizards of the Wiki](https://habitrpg.com/#/options/groups/guilds/9a163b28-ebcf-4e52-87de-5c040ed0f8f8) guild with @Alys and others (please excuse me for this).

However in this particular case Transifex does let the line to be saved despite of the two warnings: 
`Warning: The tag a has not been applied correctly in the translation.`
`Warning: The following url is either missing from the translation or has been translated`
I've just tested it, and it should work as well with the ordinary user's permissions.

Thank you @crookedneighbor once again, I'll add a comment based on your reminder to the information in the [Guidance for linguists](http://habitrpg.wikia.com/wiki/Guidance_for_Linguists) and [Transifex discussion](https://www.transifex.com/organization/habitrpg/team/6973/discussion/12845/) - which I've recently edited.

**Comment by Alys** [comment]
@SabreCat Can I encourage you to make the links "translatable" the way that @GitHubSphinx did in https://github.com/HabitRPG/habitrpg/pull/5207? When wiki translators have gone to the trouble of translating the pages, it would be nice to link directly to them.

Alternatively, can we use https://github.com/HabitRPG/habitrpg/pull/5207 if the tutorial testing will take a while?

**Comment by ghost** [comment]
@Alys thank you!
I should mention that in my commit I've invented different keys for the lines from the ones @SabreCat is using. That's why https://github.com/HabitRPG/habitrpg/pull/5207 probably won't do as a temporary solution - I believe it's better to use the keys by @SabreCat from the start as they will be the ones actually used in the end. I could make another commit syncing the keys, however @SabreCat is doing the job of a greater scale, as far as I can tell.

**Comment by SabreCat** [comment]
I can definitely move the links in to the translatable text, not a problem!

**Comment by SabreCat** [comment]
Done here: https://github.com/SabreCat/habitrpg/commit/9dc661bb5f1c34d4fd825b22040339166398895a

**Comment by ghost** [comment]
I hope after all the commits the only thing left is Click for help button. Addressing it with another commit (string is the same as in my initial commits, however, I've added a new screenshot in a pull request).

**Comment by ghost** [comment]
I've forgotten to mention, we don't have these lines on Transifex yet. Is it maybe somehow connected with the research about the Tour efficiency?..

**Comment by ghost** [comment]
@crookedneighbor please excuse me for bothering you!
I got myself slightly confused thinking about why we don't see these lines on Transifex while more recent updates to other json files are already there. I know, this case might be just because of the lack of time, or some testing with tour efficiency, but I'll really appreciate if you could help me with understanding: could you please give me a hint of what files are uploaded to Transifex - from develop or from master?

**Comment by ghost** [comment]
@paglias please excuse me for addressing you once again (my previous message here is lost due to a sync issue or deleted intentionally by moderators - in the latter case, sorry for repeating it).

We still don't see the changes in tasks.json on Transifex. It makes me thinking that changes go live from Develop skipping Master branch, while Transifex still has old versions of lines from Master. Can it be that way? And in case it's indeed that way, is it intentional?

**Comment by crookedneighbor** [comment]
@GitHubSphinx Really not sure about the exact process for getting the strings on Transifex. If I understand correctly, the strings should be resubmitted when they change, but that might be a manual process to resubmit. I am not sure. 

Re: your missing previous message, I would have seen it in an email if it was submitted, so it definitely wasn't deleted. Probably a momentary loss of connection with the site.

**Comment by ghost** [comment]
@crookedneighbor thank you for your comment! The process is manual (there's a separate ticket for making it partly automatic somewhere). And thanks to clarification by @Alys, I'm not worried anymore - for it's just the matter of the lack of time.

**Comment by paglias** [comment]
@GitHubSphinx it should be finally solved, let me know if it isn't

**Comment by ghost** [comment]
@paglias Oh! Thank you very much! Now there's plenty of work for translators! =)

**Comment by Alys** [comment]
For future reference, paglias noticed that the defaultTasks.json file had one string that was merely " " (an empty space surrounded by quotes), and that was preventing the file from being synced to Transifex due to a Transifex bug. @GitHubSphinx I'm sorry we didn't look into this when you were first asking about it.
