### ISSUE TITLE
Custom Day Start conflicts with Repeat Schedule

### ISSUE THREAD

**Issue by AndreCaseyScott** [HabitRPG/habitica#587]
Thanks for adding the custom day start feature! Unfortunately it isn't working as expected with tasks that have a repeat schedule other than everyday. 

For instance, I have certain Daily tasks that are only due on Tuesday and Thursday. Monday's I have certain Daily tasks disabled, due to weird scheduling. But since my Custom Day Start is 4am (I work nights most of the week), I am getting dinged points Monday for things that I'm not scheduled to do until Tuesday. From what I can tell, at midnight, the repeat schedule changes over (given they change from blue to yellow or red), even though Dailys haven't been scored yet. 

The expected action (I feel) is that the once the Custom Day time is reached, points are scored, THEN the repeat schedule changes over to the next day. Otherwise the repeat schedule is useless and confusing when used with the Custom Day Start. 

Not sure how this is implemented in the backend, so don't know if this is hard to fix. Can provide more info if needed to clarify or whatever.

Thanks for all your work on this! Loving the new features :)

**Comment by lefnire** [comment]
solid find, thanks

**Comment by sgtorange** [comment]
I've also run into this issue. I set my custom day start at 1 am. There's a daily that only occurs on Wedsnday so last night at midnight the day count rolled over to wednsday and I ended my Tuesday Daily with the Wedsnday task not completed cause it activated with an hour to go O.O

**Comment by dfjkla** [comment]
Same issue.

**Comment by horusofoz** [comment]
I noticed my Dailys that are meant to become active until tomorrow became active after 12:00 AM rather adhering to my Custom Day Start setting of 2:00 AM.

Minor bug but worth getting everything starting at the same time.

**Comment by AndreCaseyScott** [comment]
I don't know if there is any way to test this, but the custom day start might actually be working, just highlighting things incorrectly past midnight. 

Saturday I wanted to give myself a day off from productive things, but thinking that it was always a day ahead, I turned off Sunday in the Repeat Schedule. When my custom day start passes, I still got docked HP even though all was grey since it wasn't due in the schedule. 

Thus, my hypothesis is that even if a daily is grey past midnight, it is still counted for the current day until your custom time. I'll update with what I find, but if others can test too, that would be helpful.

**Comment by weelillad** [comment]
Custom Day Start is working, it is the mechanism for resetting Dailies that needs to change to reflect the Custom Day Start.

Even though I have Custom Day Start set to 6am, at midnight, any dailies that are checked get toggled/reset. Hence, when 6am rolls along, the daily is considered undone, and I am penalised.

This is a critical bug that breaks the functionality of the Custom Day Start, in my opinion. I think it should either be fixed ASAP, or Custom Day Start should be disabled until it is. This will save people from confusion and dead characters.

**Comment by kriscrat** [comment]
same issue here.

**Comment by wizonesolutions** [comment]
Yup, custom day starts work fine, but the coloring doesn't. If nobody else is having a shot at this, I might. It's probably trivial no?

**Comment by lefnire** [comment]
@wizonesolutions please do! i'm not working on it now, so you won't be stepping on any toes

**Comment by lefnire** [comment]
people of the ticket: this will go to https://beta.habitrpg.com if you wanna test there. will push to master after a couple days

**Comment by wizonesolutions** [comment]
working for me. custom day start 4 AM, it's 12:05. colors are correct. will check in morning when the daily update hits.

others?

**Comment by wizonesolutions** [comment]
:+1: works after cron has run. YAY

**Comment by lefnire** [comment]
Awesome, will push of prod soon

**Comment by wizonesolutions** [comment]
Cool. People watching, chime in if it works!

**Comment by AndreCaseyScott** [comment]
the custom day start highlighting seems to be working correctly on the beta
server. Nice work! :)

**Comment by lefnire** [comment]
Awesome, pushing up to prod

**Comment by dfjkla** [comment]
Still doesn't work properly, unfortunately. It's 1am on Thursday, my custom day set to end in five hours, at 6am. But I have items which are set for Thu already lit up, although they should be grey.

**Comment by dfjkla** [comment]
This has been open for almost two months, and the game is pretty much unplayable due to this. I have yet another day when I didn't get any point loss although I missed dailies. I also still have dailies I checked 24 hours ago greyed out, and the daily color/greying doesn't work properly.

Is there anything I can do to troubleshoot and hopefully help get this fixed?

**Comment by AndreCaseyScott** [comment]
Ever since the bug was fixed on Beta and pushed to Production, it has been working fine for me. 

Check that your day settings are correct. I had to switch mine from showing a day ahead as a workaround for this bug, you may have done something similar to compensate for the bug. Also check your reset day time (it's in 24hr time)

If you are still experiencing your dailies greying out too soon, let us know (along with your settings, maybe a screenshot or two)

**Comment by dfjkla** [comment]
I don't know how to set the day to be one day ahead. I have set day to end at 6am.

They are not greying out too soon. I have items which were only set up for Wed shown in color on Thu.

Also, checked items stay checked for 24 hours, and do not reset at day end (6am). I suspect this is because I check them after midnight, and the system doesn't take custom day end into account.

**Comment by Shaners** [comment]
@dfjkla are you using multiple computers / environments to check things off?

**Comment by dfjkla** [comment]
No, just one. Opera on PC. Tried it on FF, and same issues occur.

**Comment by dfjkla** [comment]
Died again due to this.

Custom day set at 6am. Things stay checked for 24+ hours, until custom day end.

**Comment by wizonesolutions** [comment]
Can you do a Jing video or take a screenshot showing your computer's time and your custom day start? Something to put some visuals to what's happening.

**Comment by dfjkla** [comment]
Custom day start at 6am local/computer time. I enter my activities after midnight every day, but before 6am. These activities remain checked until 6am the following day, ie. more than 24 hours.

I suspect this is because HabitRPG honors custom day start in only some of the background processes.

**Comment by AndreCaseyScott** [comment]
I always end up checking things round 2 or 3am my time [custom day start
set at 4am] and I've never had a problem with this. All seems to work fine
since the fix went live. The only issue that I had was that the _color_ of
the active tasks would be off due to the custom day start time. I did some
testing as to your issue before the fix was implemented, and was unable to
recreate. Like Kevin said, you need to send some screen shots or something
to illustrate this.

Any coders know of other helpful info? Maybe something he can send from the
inspect panel or firebug? :/

**Comment by dfjkla** [comment]
ok, I'll post screenshots within 48 hours to show the progression.

**Comment by dfjkla** [comment]
Reproducing the bug is a bit painful as it seems to step over a day every time. Hopefully below screenshot clarifies.

http://imgur.com/8RJkZNq

**Comment by lefnire** [comment]
this should be fixed now in https://github.com/lefnire/habitrpg/commit/92b178b4a41eb96e24449f1bef3e379e85590bae - should calculate day-diff properly, color-coding, etc. Please re-open if you experience any more

**Comment by dfjkla** [comment]
Not fixed, still same issue.

**Comment by AndreCaseyScott** [comment]
I definitely sent this 5 days ago...guess I was right to not trust replying to these things via email >_<

Its interesting to note that just the other day, I also experienced this bug. First time this happened to me. I checked a bunch of things off on my phone around 11pm (via Chrome Browser on Android 4.2), checked it around 1pm the following day (my custom day resets at 4am) and they were still checked. Refreshed several times to check. The only way I know this was not just a refresh issue on my phone, is that my streaks didn't all go away when I didn't use HabitRPG for a whole day! [not logging into HabitRPG for a whole day! crazy I know :P]

My thoughts currently revolving around issues with accessing HabitRPG on different devices, which was mentioned elsewhere. Will update if it happens again. Anything I can check client-side to help identify issue if it does happen again?

@dfjkla - Do you access HabitRPG on multiple devices? i.e. more than one desktop, desktop and mobile device (smartphone or tablet), etc.

UPDATE: Has not happened since, and I haven't checked Habit from my phone this week...

PS - not sure why the text is so big at the top...not intended

**Comment by lefnire** [comment]
Expect some big fixes to things in the coming week. Firstly, we've moved most logic off the website and into a shared library https://github.com/habitrpg/habitrpg-shared . We did this so we can port logic to the mobile app, and anyone else that wants - but the side effect is it lets us write unit tests, so we can make sure these scheduling bits aren't buggy. Additionally, I'm going to be experimenting with the new Racer / Derby v0.5, which purports to have solved most of these multi-computer syncing issues.

**Comment by startmyquest** [comment]
I experienced this problem today I think. Did not manage to login to habitrpg whole of yesterday, but today streaks are still present and no penalties from not doing my daillies.

Start time remains at default. All dailies are set for every day, no specific selections. Its a very simple set-up as I've only just started using the site. Still at lvl 1 :)

I do access HabitRPG on multiple devices, but not yesterday. Desktop at work, tablet and home computer, only on Friday.

I'm happy to have been given a reprieve from yesterday, but kind of defeats the objective if this isn't working. [Must fight urge to cheat...]

**Comment by dfjkla** [comment]
Back from vacation, was in the tavern for several weeks - and I still have several checked items in my todos.

I only use HabitRPG on one device (PC).

**Comment by lefnire** [comment]
@dfjkla that's by nature, first day you come back everything remains exactly as you left it, rolls over the next day. this to prevent checking into the inn right before new day (cheating) see https://trello.com/c/A2w2orSc/14-rest-in-tavern for the conversation

**Comment by dfjkla** [comment]
It's 24+ hours later, and they're still checked - the bug is still unfixed.

**Comment by AndreCaseyScott** [comment]
And you've made sure to refresh the page? With the current issues with the
backend framework, a refresh is required if the window is left open for a
while. Items will stay in their current state (or not save if you continue
checking items off) unless a refresh or page reload as occurred recently.

This should hopefully be fixed automatically with the angular.js rewrite

**Comment by dfjkla** [comment]
I did refresh.

It appears the bug is the same as in the past: the checkmarks stay for two days, then reset. I'll continue to track it, as this continues to be a gamebreaking bug.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by dfjkla** [comment]
This still happens occasionally even with the new build. I've had it happen three or four times since it launched, latest today. Yesterday I refreshed before and after updating, yet I still have checked items in my game today.

Custom day start at 6am, I checked the items around 2am.

**Comment by AndreCaseyScott** [comment]
I have actually had this happen too. It was always so random, and I noticed it via the Mobile app thus couldn't check the console. It would stay in the same state even if I checked the computer later that day. Would reset the next day. Will keep an eye on it, for more conclusive evidence. 3am reset time. 

@dfjkla if you notice it again, check the javascript console and post any errors here

**Comment by dfjkla** [comment]
How do I check the javascript console?

**Comment by paglias** [comment]
On chrome you can open it with CTRL+Shift+J

2013/10/9 dfjkla notifications@github.com

> How do I check the javascript console?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/issues/587#issuecomment-25954666
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by lefnire** [comment]
Is this due to the Monday / Sunday international thing? Can't remember if
we fixed that or not..

**Comment by dfjkla** [comment]
Thanks, both. It did happen on Monday local time. Week starts on Monday over here, don't recall if there's a setting somewhere about that.

I'll keep you posted if/when it re-occurs!

**Comment by dfjkla** [comment]
Now it happened overnight between Sat/Sun. I checked items after midnight on early Sunday morning, got damage during the night (custom day start at 6am), but the checked items are still checked the following day (Sun).

**Comment by dfjkla** [comment]
This gamebreaking bug still happens, twice this week alone. Any progress?

**Comment by AndreCaseyScott** [comment]
I had this happen a few days ago, think it was related to me checking in
with the official app. Still no idea what actually triggers it. Happens so
randomly. After the api fixes last time, it rarely happens to me now. But
still annoying.

**Comment by AndreCaseyScott** [comment]
Happened again, just now. Had tab open for a while, well past my custom day start. Refreshed page to check off new dailies. nothing reset. no errors in console. 

This could be problematic with challenges. I have an unbroken streak on one of my tasks I know I've done for 24 days, only registers 19 days in Habit. Others in the challenge are showing 24 days. The chart shows no drops from not being checked. 

at a loss...

**Comment by paglias** [comment]
I think we can safely say this is the same as #1057

**Comment by dfjkla** [comment]
Yes, it is. This was opened in March, and 1057 in May, though.

**Comment by paglias** [comment]
@dfjkla Yeah I know but we did most of the discussion there so it's better to use it
