### ISSUE TITLE
Excessive/Inappropriate Points/Levels Received

### ISSUE THREAD

**Issue by inbasso3** [HabitRPG/habitica#594]
I had been struggling just to stay alive lately, but I noticed that yesterday I was up to Level 3, and today I am unjustifiably way up in levels and points (Level 28). I also noticed that when I hit the (-) button for doing poorly with a habit, it seems to give me positive points? This is totally contradicting the purpose of the game, so I hope it's a simple bug!

**Comment by PhilipHow** [comment]
Yeah we've been having problems with the formulas at the moment, and we've done some balancing and fixed some bugs.

Can you confirm what happens when you click a negative habit? It definitely shouldn't be giving any points!

You can restore your level to 3/4/5 or whatever you want on the settings panel. Just click the restore button.

We'll be rebalancing things soon, but out of interest, can you check off your oldest todo and tell me how much XP it gives? You can uncheck it again after!

**Comment by inbasso3** [comment]
Actually, it's giving me "Level Up!" when I click on a (-)

When I checked off my oldest undone To Do, it gave me +73.2 XP, with -11906.8 XP below it, also in purple, Level Up, and +4 gold coins, 40 silver coins

**Comment by PhilipHow** [comment]
So you're current XP is larger than your level, which is causing the level ups when you click a (-). This should be fixed now!

**Comment by Nousagi** [comment]
I have been suffering from a similar issue for about a week and a half. Today, this bug has reached epic and hilarious proportions. Observe my Level 124272331 character.

![rpg bug](https://f.cloud.github.com/assets/3781247/225087/ac07b130-85e7-11e2-9085-ca87b06b4022.JPG)

**Comment by mfcovington** [comment]
@Nousagi May I borrow some of that silver?! I think you have over a quadrillion [moles](http://en.wikipedia.org/wiki/Mole_%28unit%29) of silver coins...

**Comment by Pandoro** [comment]
Darn ! That is hilarious indeed, sorry if I say so x)

I also couldn't help looking through your setup! I hope the bunny salad is
actually.... for the bunny and not a salad of your pet bunny. And I am
wondering are you playing world of warcraft as a + or a  - habit ;)

nyways. If you want to go back to normal again, you can restore your
account to the "original" values, which you can find in settings -> scroll
down -> restore. There just set your desired values and items and you are
good to go again. I think in general the stuff should be fixed and these
bugs should no longer occur.

**Comment by Nousagi** [comment]
Hahaha, the bunny salad is, in fact, a salad for my bunny, Oscar Wilde, who is terribly spoiled.

And my husband went through a few weeks ago and added a bunch of habits. He didn't think I was playing enough WoW.

I tried the restore thing, which took two tries, as the first time the game tried to give me more than 500,000 health. Now it seems to have stuck, but now I gain now EXP or gold for completing tasks!

**Comment by Pandoro** [comment]
Hehehe, that is funny xD 

Sorry for the inconvenience :( 
Have you tried refreshing the page? I don't think that the restore function should affect the gaining of exp. Other bugs have caused buggy stuff like this in the past, but it was always temporary due to server load etc. So if this keeps happening in the next few minutes, please report back so someone can look into this in detail!

I just hope you are the first and not one of the many users who has had this problem after restoring x.x

**Comment by Nousagi** [comment]
Yep, still happening. I've tried several combinations of settings through restore (apparently, if you don't put a value in for Level, you are level NaN?), and nothing continues to happen when I click things. Sad. ;_;

**Comment by Pandoro** [comment]
@Nousagi so have you tried to set an actual level there as well? I think it is critical for the current system that it has a valid level.

@lefnire Maybe it is time you look into this as well. Not only into this special case, but also maybe change the restore function so that the NaN case is excluded in any way :x

**Comment by Nousagi** [comment]
I set the actual level at 1. I also tried giving myself 1 Exp, so that value wasn't NaN. 

Still nothing.

**Comment by Pandoro** [comment]
Hmmm I tried to reproduce this on the test server, but sadly I was not able to do so. 

Even after leaving all fields blank, (for me everything also was set to NaN), I could restore it to a different value and it was working fine again. Maybe through some weird case some value was set to NaN which cannot ne reset through the restore menu. For that 

Does it happen for everything you try to complete? Habits, dailies, todos? Also maybe try to create some new dummy tasks, as these should have clean values everywhere. Do you btw get no response at all? Or do you see something like 0 exp and 0 gold notifications ? 

@lefnire any thoughts on this?

**Comment by lefnire** [comment]
I'm not quite following what's happening. So (1) using the restore tool, if you don't enter numerical values you get NaN? I can add some `?=` fallbacks there. (2) Now that you're restored (after figuring out the tool's issues), what seems to be the problem?

**Comment by Pandoro** [comment]
The problem is that @Nousagi cannot gain any exp from completing tasks
after restoring to some values. Also when correctly setting values for all
the fields.

**Comment by Nousagi** [comment]
I get not response at all, for habits, todos, anything. I can also deselect my dailies after checking them, something I don't think I can usually do. If I give myself gold, I can buy things, but that's the only functionality I have at the moment.

**Comment by lefnire** [comment]
Can you [email me](mailto:tylerrenelle@gmail.com) your UUID (or user name, or email) ?

**Comment by Jennklem** [comment]
I'm having the same problem, completed one task and got millions of XP and gold, and bumped to level 545.  :(

**Comment by lefnire** [comment]
@MrConcept, does the latest algos merge (today) fix these issues?

**Comment by Pandoro** [comment]
@lefnire, as far as I understood, the stuff should have been fixed already,
but the OHV was not changed for old tasks, that what is causing the
problems. I am not sure if this was actually fixed, or that is what the
migration scripts were needed for.

This will probably not fix the "I get nothing for checking stuff" error
though :x

**Comment by Nousagi** [comment]
Yay, it works again! Thanks doods!

**Comment by lefnire** [comment]
great, fixed. and the excessive points stuff should be fixed too. re-open if anyone experiences issues
