### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by IstraLouise** [HabitRPG/habitica#6700]
When I go to visit the guilds I'm immediately greeted with an Application error:

Yikes, an error occurred! Please reload the page, your last action may not have been saved correctly.

"Error 

Reloading the page does not work. 

Windows OS: 10  Firefox Browser: 44.0 UserID: f3d96171-562a-4100-a78e-a3792981d837

_edit by admin_:
### What to do if this happens to you:

**This error can be caused by either a local problem, or can be site-wide for many users.**

**When it's a local problem, reloading the page often fixes it, and that's the first thing you should try. If that doesn't work, log out of Habitica and log back in. If the error message is blocking the Settings > Log Out menu entry, you can either zoom out to about 10% or go to https://habitica.com/static/clear-browser-data and click the button there.**

**When it's side-wide for many users, reloading or logging out might not help, or might work only temporarily. Comment here if you can't make the error stop (although if you see that a few people have already commented in the past few minutes, you can be certain we already know about it and you don't need to add another comment). We will then restart the server, which generally removes the errors.**

<img width="262" alt="screen shot 2016-01-07 at 8 23 19 am" src="https://cloud.githubusercontent.com/assets/3885681/12175615/2c007ee6-b518-11e5-9e2a-969d256aedfc.png">

**Comment by nelle013** [comment]
Same issue. on all of the site for me. even tried logging out and logging back in on a different page. About to try a different browser as I was just on Chrome

**Comment by Cartogenic** [comment]
You're not the only one. I've been having those, quite a lot as well, since yesterday.
People in the tavern also complain.

This is quite annoying

https://i.imgur.com/jFHgVOv.png

https://i.imgur.com/hUZgEeB.png

**Comment by Cartogenic** [comment]
It appears to be a server flood problem, due to a spike in the amount of users utilizing the platform (mod said it in the chat). In which case servers should probably be upgraded.

Each day I see these errors is another day I regret having bought subscription in habitica for 13 months.

**Comment by Endroine** [comment]
I have the same issue, on the whole website. I can't complete tasks since it immediately says error, and doesn't save it. (or anything for that matter) It really makes me want to quit this thing x.x

**Comment by Cartogenic** [comment]
Yup, what's the use of it if I can't mark dailies and todo's as "Done", or create/delete new ones. Even party chat doesn't work properly. Might as well use pen and paper for TO-Do's.

**Comment by Dewines** [comment]
I understand that the "Yikes!" error message is due to server issues and that people are working on a solution. What I wondered was, do the messages have to persist on the screen? It means I can't read the chat that has loaded! Any chance of them fading away after a few seconds, like the drop notifications do?

**Comment by raphrfg** [comment]
I can confirm that I am having the same issue. Win8.1/Firefox 44.0.2.

**Comment by Taylor-J-Holmes** [comment]
Same problem here. Win 10. Really frustrating issue. Habitica's supposed to help create habits, not stop us from doing so.

**Comment by Alipan** [comment]
Same here.  Chrome version 48.0.2564.103
What is being done to handle the surge in users?  

These are the error codes.  
https://habitica.com/common/dist/sprites/spritesmith-main-2-81f53ce8.png Failed to load resource: the server responded with a status of 503 (Service Unavailable)

https://habitica.com/api/v2/challenges/8c95843e-c5f1-4245-9506-98008af11b33 Failed to load resource: the server responded with a status of 503 (Service Unavailable)

app-c14655c7.js:32 Object

**Comment by lemoness** [comment]
We're very sorry about these problems! I know that it is incredibly frustrating to constantly experience these errors. We've been working hard to address them over the past week. It seems to be combination of server load, since a bunch of new users came in from Imgur, and database load, a much harder problem to fix. We're monitoring our servers and working with the people who run our database, and we've been trying out several different solutions. Fixing this is our top priority right now! 

Thank you all very much for your patience, and for taking the time to report the errors to us. For those of you who have lost stats, you can restore them on the website under Settings > Site > Fix Character Values. Please don't hesitate to let me know if you have any more questions or need additional assistance.

@Cartogenic Thank you so much for purchasing a subscription. I'm sorry that it feels like a waste! It's during times like that we are most grateful to subscribers like you, since these fixes are often expensive and we don't have a lot of extra room in the budget. We won't rest until we get back to our usual stable self. That being said, if you really want to quit, we will understand if you email us at admin@habitica.com and request that we refund your subscription. Just let us know.

**Comment by lemoness** [comment]
We've deployed some changes that we hope will increase stability, and are now monitoring site performance. In the meantime, please let us know if you experience more errors! Thanks again for your patience as we work to restore the site to its normal stability.

**Comment by troutmonfalco** [comment]
I'm experiencing this for the first time today. It continually pops up (even multiple overlays next to each other) even when I'm doing nothing, with the Task window sitting in the browser. (Assuming AJAX call in the background is returning the errors). The first time it happened I reloaded and the overlaid messages  said "-15 Experience, -2 Silver." I'm not sure if it registered them twice and corrected or now I'm lower than I'm supposed to be. It's still happening at this very moment (8 pm, PST). I'm in Safari 9.03 / Mac OS X 10.10.5.

**Comment by Alys** [comment]
@troutmonfalco If it's still showing the errors, try logging out of Habitica. Clearing cookies might also help. 

The apparent loss of experience is just the site showing you that it has reversed actions you took that could not be saved permanently to the server. Look for Dailies or To-Dos that you previously marked as completed but that are now uncompleted.

**Comment by troutmonfalco** [comment]
I had closed the Habitica browser window since reporting the error. When I just loaded the page the errors seem to have disappeared. Here's hoping whatever they are trying is working :)

**Comment by Endroine** [comment]
I haven't had errors since. Thanks so much!!

**Comment by nelle013** [comment]
Me neither. Though I did switch to when I was getting errors and it was
fine on there... I'll switch back to Chrome now.

On Sat, Feb 13, 2016 at 8:40 AM, Endroine notifications@github.com wrote:

> I haven't had errors since. Thanks so much!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-183679051.

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by troutmonfalco** [comment]
Sorry but it's happening again... :/ 6 pm, PST. Same browser and environment as before. This time when adding a task.

**Comment by Alys** [comment]
@troutmonfalco Thanks! I've just restarted the server, which should fix it for a while.

**Comment by notapooka** [comment]
I've been encountering this issue pretty consistently since Friday. I've only been able to complete tasks on the first time late at night PST, and most of the time I have to reload the page 5+ times to complete a single task or even check one item in a checklist.

**Comment by dargolith** [comment]
Same issues for me. Things aren't registering correctly. Bars jump back and forth (on page reload). Server-side doesn't seem to register changes. Getting lots of service unavailable errors to console.

Service is simply not usable right now. Honestly though, I've seen those errors since I started my account, just not as frequently as lately. Server seems pretty unstable overall.

**Comment by zlionsfan** [comment]
I got some of the same 503 Service Unavailable errors in Win7 Firefox today - I had visited recently, but had restarted my computer since then. No issues at first, but after Backstabbing tasks, I started to get them, and I get them now on each page if I wait long enough. It all seems to be from the same call: https://habitica.com/api/v2/user/batch-update?_v=1919&data=1455510330378

However, I logged in through Chrome, where I've not logged in before, and have not yet seen an error, even after Backstabbing tasks. I also noticed that the stats and drops I got from the Firefox session, plus the frequency of the Habits I checked, are still here, but my experience and mana did not reflect that activity - repeating the Backstabs got me the experience again.

Aha. I reproduced the error by patiently working through tabs in the Social section. I may not have been waiting long enough on each page - the activity indicator in the upper left is still spinning. 

Sure enough, I'm getting the same errors on any page in Chrome now - the 503 error hitting the API (although this call is https://habitica.com/api/v2/groups?type=guilds), and what I'm assuming is an error from using an ad blocker (because it comes from a call to google.com/ads/... and is ERR_BLOCKED_BY_CLIENT.

**Comment by SmashyMcGee** [comment]
I keep getting the same error others have reported. It's been on and off all week but now I can't seem to do anything, including but not limited to adding items to my lists, checking them off, leaving a party or adding checklist items.

**Comment by kotylw** [comment]
Having a similar issue as well.  Started a week ago and has slowly gotten worse.
User ID: 0eeeb347-64ca-4321-9b81-a7408de63ad1
![errorhabitica](https://cloud.githubusercontent.com/assets/16230029/13052210/9b783fd0-d3cb-11e5-96ea-8bd40e05fc08.png)

**Comment by chondrus** [comment]
I've been hitting 503 errors pretty consistently since friday at least. I hope the site is stable soon!

**Comment by Mark-Eng** [comment]
Been getting this error for a few days. OS: Windows 10; Browser: Firefox 44.0.2. Attached file has the error message from the console.

[Habitica Error.txt](https://github.com/HabitRPG/habitrpg/files/131121/Habitica.Error.txt)

**Comment by nelle013** [comment]
It had cleared up for me... but this morning must have a lot of server
traffic creating more bugs.

On Mon, Feb 15, 2016 at 10:47 AM, Mark-Eng notifications@github.com wrote:

> Been getting this error for a few days. OS: Windows 10; Browser: Firefox
> 44.0.2. Attached file has the error message from the console.
> 
> Habitica Error.txt
> https://github.com/HabitRPG/habitrpg/files/131121/Habitica.Error.txt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-184294920.

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by Cartogenic** [comment]
Errors continue for me..

![Error](https://i.imgur.com/aBE1t1X.png)

![Error2](https://i.imgur.com/hUZgEeB.png)

**Comment by lemoness** [comment]
Hey everyone -- I just wanted to give you all an update on what we're doing about the errors!

As you have discovered, the changes we made on Friday helped reduce the errors to a degree, but they're still occurring too frequently, so we've continued to work on other solutions this weekend. Currently we are in communication both with the people who run our servers and the people who run our database, working to figure out how to return to our usual stability. In the meantime, we are implementing some tools to automate restarts, which should decrease the errors as well. It's not a permanent solution, but it should help take off some of the strain. 

Once again, we are very sorry about the hassle, and we want to thank you all for being so patient and for helping us out by reporting the errors as they happen. For those of you who have lost stats, you can restore them on the website under Settings > Site > Fix Character Values. Please feel free to ask if you have any more questions or need help with anything!

**Comment by ghost** [comment]
This is still happening for me and my party in Chrome v. 48.0.2564.103

![a30a58d7-95a0-4050-96bd-8be5347070ee](https://cloud.githubusercontent.com/assets/4099794/13148106/db7f3574-d629-11e5-8696-09cb04859f31.png)

**Comment by Cartogenic** [comment]
here we go again...
![...](https://i.gyazo.com/22cb441ab4ed33bbcd130e951bcdb7b9.png)

**Comment by Cartogenic** [comment]
I can't even access the page ![](https://i.gyazo.com/4271d046b6ff767582077c274646d5e5.png)

**Comment by lemoness** [comment]
I've just restarted things -- it should be working again now. We apologize
for this! Let me know if you keep having trouble.

**Comment by Cartogenic** [comment]
Here we go again....and again...and again...everyday, around lunch for a few hours...this is not fun :/
![](https://i.gyazo.com/088ae75e4603d684fda33efb862a74d2.png)

**Comment by nelle013** [comment]
I have an error popping up on both app and safari mobile. 

Janelle Rowe
School Psychology Student
University of Alabama

**Comment by Endroine** [comment]
Hi!
I now have:
503 Service Unavailable
No server is available to handle this request. 

And the app on my phone says it cant connect to the internet while I have internet (I am sure of that)
=( i know you're doing your best, keep it up <3 =D

**Comment by paglias** [comment]
@Endroine things should be better now. Can you try reloading the website?

**Comment by paglias** [comment]
@Cartogenic @nelle013  things should be better now. Can you try reloading the website?

**Comment by Endroine** [comment]
Heyy, i still have the same issue on the website. I originally tried in Firefox, but i also tried in chrome now and it says the same thing (503 Service Unavailable) The app seems to work fine now, but i don't trust it for 100% yet =p

**Comment by notapooka** [comment]
I'm still getting 503 Service Unavailable errors, as well. Once, reloading took me back to the Habitica home page (I guess I got logged out?), but clicking Play Now didn't get any response, and when I reloaded again it was back to 503 errors.

**Comment by nelle013** [comment]
It's working for me.

On Sun, Feb 21, 2016 at 2:42 PM, notapooka notifications@github.com wrote:

> I'm still getting 503 Service Unavailable errors, as well. Once, reloading
> took me back to the Habitica home page (I guess I got logged out?), but
> clicking Play Now didn't get any response, and when I reloaded again it was
> back to 503 errors.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-186910835.

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by nelle013** [comment]
Okay. Now I'm getting just Error... I'm on Chrome now.

[image: Inline image 1]

On Sun, Feb 21, 2016 at 3:08 PM, Janelle Rowe puppyrowe@gmail.com wrote:

> It's working for me.
> 
> On Sun, Feb 21, 2016 at 2:42 PM, notapooka notifications@github.com
> wrote:
> 
> > I'm still getting 503 Service Unavailable errors, as well. Once,
> > reloading took me back to the Habitica home page (I guess I got logged
> > out?), but clicking Play Now didn't get any response, and when I reloaded
> > again it was back to 503 errors.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-186910835
> > .
> 
> ## 
> 
> Janelle Rowe
> University of Alabama
> School Psychology Program PhD Student
> 585-727-8433

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by Alys** [comment]
This should be working for everyone now. If anyone is still getting 503 Service Unavailable errors, please comment again here.

**Comment by Endroine** [comment]
Thank you so much again! It is working, yay!

**Comment by Cartogenic** [comment]
yeah just wait a few hours you'll start seeing errors again :/

**Comment by Alys** [comment]
@Cartogenic Can you describe the problems you're having now, please? For example, are you seeing the typical red application error boxes on the website, or are you getting a plain 503 error with nothing else at all showing up on the page? Does the error you're seeing now disappear when you reload, and if so, roughly how long until it comes back? Is there any other information you can give us about what you're seeing now?

**Comment by Cartogenic** [comment]
@Alys Check my previous posts in this thread, above I have posted several screenshots, In different days.

It's just Application error, and page doesn't load or takes few centuries to load. Other times dailies and to-dos just cannot be ticked off, the upper loading bar stops at like 97% and then shows application error popup. 

And even when I think they are finally ticked as done, when I come back after a while, they are still there waiting to be completed.

And sometimes, apparently I'm not in a party anymore.

I usually get the errors around 15:00~~16:00 or so (gmt +00:00), I'm guessing peak hours and RIP server resources, and requests don't go through.

**Comment by SmashyMcGee** [comment]
I've been getting red box application errors a lot today with explorer and with my andriod app. Reloading is fixing the errors 50% of the time (less on the app).   Especially if I was checking off a few items.  

I also have noticed that I am not in a party anymore like @Alys but where it seems like I disappear from my party on my end the other people still see me as active (I know them irl so its easier to check) and then it reappears on my side like an hour later.

**Comment by esmanning** [comment]
I was just getting these repeatedly for about 20(?) minutes. Mostly I was getting the red box, and when I refreshed the page would look okay again, maybe sync for a couple clicks of a Habit, then red-box again. There was also a plain 503 error page at least once in there.

**Comment by Alys** [comment]
@Purplatypus We haven't seen other reports, or noticed them ourselves, so this particular case might be in your browser. If they're still happening, can you try logging out of Habitica and clearing cookies? I'll use Habitica more than usual over the next hour to see if I notice any problems.

@SmashyMcGee When you seem to not be in a party, it's almost always just that the party information hasn't been loaded into your browser in time to appear before a timeout or other error happens. It's not that you were actually dropped out of the party (although there are some exceptions caused by unusual bugs, but they're very rare).

**Comment by nelle013** [comment]
getting some more "Error" messages right now... this time period must be
very popular.

On Sun, Feb 21, 2016 at 3:12 PM, Janelle Rowe puppyrowe@gmail.com wrote:

> Okay. Now I'm getting just Error... I'm on Chrome now.
> 
> [image: Inline image 1]
> 
> On Sun, Feb 21, 2016 at 3:08 PM, Janelle Rowe puppyrowe@gmail.com wrote:
> 
> > It's working for me.
> > 
> > On Sun, Feb 21, 2016 at 2:42 PM, notapooka notifications@github.com
> > wrote:
> > 
> > > I'm still getting 503 Service Unavailable errors, as well. Once,
> > > reloading took me back to the Habitica home page (I guess I got logged
> > > out?), but clicking Play Now didn't get any response, and when I reloaded
> > > again it was back to 503 errors.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-186910835
> > > .
> > 
> > ## 
> > 
> > Janelle Rowe
> > University of Alabama
> > School Psychology Program PhD Student
> > 585-727-8433
> 
> ## 
> 
> Janelle Rowe
> University of Alabama
> School Psychology Program PhD Student
> 585-727-8433

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by ghost** [comment]
quoting myself from #6749

> severe sync issues during past hour or so

**Comment by lemoness** [comment]
In this case, there's actually an additional complication - Heroku is
undergoing maintenance right now! Things should be working again for us if
you refresh, but we are monitoring closely while they're doing maintenance,
because there may be additional trouble that we need to handle. Hopefully
they will be done with it soon.

**Comment by ghost** [comment]
`just kidding`  @lemoness must have been bad luck for me then... and for my party... two days in a row

Have a nice and productive day, everyone! (and Heroku too) =)

**Comment by Cartogenic** [comment]
So I'm not in a party anymore apparently....loads forever. is this due to maintenance?

![](https://i.gyazo.com/2aa6bd15b6feacbbf8b9362feba6e36e.png)

**Comment by MegBookworm** [comment]
I have this problem as well, and have reloaded the page 5 times. Still doesn't work. I even went from Wi-Fi to ethernet cable, and still no difference. Any suggestions? I'm in the middle of a boss battle, and trying to mark my dailies so I don't lose health or get into the Inn.

It loaded in all text once, and now won't load at all. It's just giving me a straight Application Error. Again, any help would be appreciated!

(To note when it happened, it was working just fine a little over an hour ago. Though the one Application Error did show up, it disappeared after I reloaded the page.)

**Comment by Alys** [comment]
@MegBookworm We restarted the server a few hours ago. Is the site working for you now?

**Comment by MegBookworm** [comment]
@Alys It's working now. Thank you so much!

**Comment by gamergemparq** [comment]
http://prntscr.com/afv53m

Hi, 

Happens to me today. Reloaded the page, error still happens.

Happened to me last time, when there was an announcement popup as well. Maybe the popup is the culprit?

**Comment by ghost** [comment]
Experiencing right now

**Comment by nelle013** [comment]
I'm experiencing a server error on the Chrome website right now. The page
won't even load properly.

On Wed, Mar 16, 2016 at 8:20 AM, Sphinx notifications@github.com wrote:

> Experiencing right now
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-197324505

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by nelle013** [comment]
Is working on Safari.

On Thu, Mar 17, 2016 at 9:37 AM, Janelle Rowe puppyrowe@gmail.com wrote:

> I'm experiencing a server error on the Chrome website right now. The page
> won't even load properly.
> 
> On Wed, Mar 16, 2016 at 8:20 AM, Sphinx notifications@github.com wrote:
> 
> > Experiencing right now
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-197324505
> 
> ## 
> 
> Janelle Rowe
> University of Alabama
> School Psychology Program PhD Student
> 585-727-8433

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by nelle013** [comment]
Okay guess it was just a short glitch... it's working on Chrome again.

On Thu, Mar 17, 2016 at 9:38 AM, Janelle Rowe puppyrowe@gmail.com wrote:

> Is working on Safari.
> 
> On Thu, Mar 17, 2016 at 9:37 AM, Janelle Rowe puppyrowe@gmail.com wrote:
> 
> > I'm experiencing a server error on the Chrome website right now. The page
> > won't even load properly.
> > 
> > On Wed, Mar 16, 2016 at 8:20 AM, Sphinx notifications@github.com wrote:
> > 
> > > Experiencing right now
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/HabitRPG/habitrpg/issues/6700#issuecomment-197324505
> > 
> > ## 
> > 
> > Janelle Rowe
> > University of Alabama
> > School Psychology Program PhD Student
> > 585-727-8433
> 
> ## 
> 
> Janelle Rowe
> University of Alabama
> School Psychology Program PhD Student
> 585-727-8433

## 

Janelle Rowe
University of Alabama
School Psychology Program PhD Student
585-727-8433

**Comment by ghost** [comment]
I'm experiencing the problem described in the ticket now

**Comment by lemoness** [comment]
Everyone, we have just finished migrating our servers. Under the new system, we have more alarms and systems in place to alert us and fix things if a server starts to collapse, so we are hopeful that this will lead to much more consistent stability for Habitica. As always, please do let us know if any of you continue to experience problems -- it really helps us out.

Thank you so much for your patience, and please feel free to ask if you have any questions!

**Comment by nelle013** [comment]
503 Error Can't access site on Chrome or Safari... tried different
computers as well.

**Comment by Alys** [comment]
Sorry @nelle013! We're working on this as fast as we can!

**Comment by nelle013** [comment]
Thank you!! I feel like a fish out of water when Habitica isn't working.

**Comment by Alys** [comment]
@nelle013 We know how you feel! 

Everyone, the site is back for us now although we're still monitoring it closely to make sure it's okay.

**Comment by crookedneighbor** [comment]
We've moved off the hosting provider where these kind of errors manifested and the code base has changed substantially where if this kind of thing happens again, it'll be more useful to start a new issue rather than pile onto this one, so I'm closing it.
