### ISSUE TITLE
Link to FAQ broken

### ISSUE THREAD

**Issue by ghost** [HabitRPG/habitica#752]
When I try to open the FAQ on the bottom of the page, it links to http://community.habitrpg.com/faq-page. Here it only says "Access denied You are not authorized to access this page."

**Comment by wc8** [comment]
I think I'm fixing this, hang on.

**Comment by wc8** [comment]
I believe this should be fixed now. If not, reply back.

**Comment by fawques** [comment]
Now it works, although the redirect is a little buggy in Firefox (Windows 8).
When you press the back button, it sends you back to https://habitrpg.com/static/faq, which redirects again to http://community.habitrpg.com/faq-page.

**Comment by paglias** [comment]
Hi! The site has been totally rewritten from the ground up, I'm closing the issue since it's probably fixed. Check if it's still happening and in case reopen the bug, thanks!

**Comment by ghost** [comment]
I was just looking at the issues I've posted in the past and noticed this one again. The link to the FAQ at the bottom of the screen works just fine. However, the link to the FAQ in the sidebar of the community site is still broken.

**Comment by lefnire** [comment]
woops, gotcha. updated
