### ISSUE TITLE
Check-in counter at User > Profile is broken: next{{::getProgressDisplay()}}

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8412]
As reported by RandomGryffindor in the Reprt a Bug guild:

Now at the User>Profile where you can see your check-in counter, it says: Progress until next{{::getProgressDisplay()}}.

![image](https://cloud.githubusercontent.com/assets/1495809/21959324/369190b0-dabb-11e6-8888-94b6b0cb0d89.png)

**Comment by hur** [comment]
The progress display works fine for me.
![](http://i.imgur.com/F5LQWtz.png)

**Comment by Alys** [comment]
@hurbraa Sorry! I should have specified that this bug is for players who have more than 50 check-ins (because we don't yet have support for more than that).

**Comment by librarianmage** [comment]
Would you like it to be something like "Progress until next: ???"

**Comment by Alys** [comment]
Since this bug should (I think) only happen when we haven't yet added new incentives to the website, it's probably best to replace "Progress until next..." with a different message. Perhaps:
**"New check-in incentives will be added soon!"**

@lemoness How does that sound?

By the way, it's possible that the new incentives will be added before this bug is fixed, but I still think it should be fixed, in case this situation arises again in future.

**Comment by lemoness** [comment]
I think that phrasing works well!

**Comment by mandyzhou** [comment]
This still seems broken -- it no longer says "Progress until next", but it does still show "{{::getProgressDisplay()}}".

**Comment by gsacavdm** [comment]
I've submitted a PR for this and a new rev for it.
Can the tag for this be updated to in progress?
