### ISSUE TITLE
API allows quests to be purchased and started without fulfilling eligibility requirements

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#8530]
In the Report a Bug guild, Birkwelch writes: 
"I previously mentioned a minor bug in the Android app about being able to start a quest without having completed the requirements; apparently you can also purchase any quest without fulfilling eligibility requirements, i.e. you don't have to be level 60 to purchase Recidivate, or have completed the first two parts to obtain part three."

Even though that can be done on the Android app (and possibly also iOS), the root cause is that the API doesn't enforce the eligibility requirements.  NOTE THOUGH: I have not confirmed that myself. If someone would like to do a test and report the results here, that would be great!

Assuming that's correct, the API should be changed to:
- make it impossible to buy a quest if you aren't eligible to do so
- make it impossible to start a quest if you aren't eligible to do so
- return an informative error message for both those cases
- have the error message documented in the API in an `@apiError` comment
- have tests for the new behaviour

**Comment by Alys** [comment]
Argh, sorry, hit enter way too early! Am fixing this now with a shorter title and proper first post. Will delete this message when I'm done.

**Comment by Alys** [comment]
I've fixed the title and updated the top post with this information:

In the Report a Bug guild, Birkwelch writes: 
"I previously mentioned a minor bug in the Android app about being able to start a quest without having completed the requirements; apparently you can also purchase any quest without fulfilling eligibility requirements, i.e. you don't have to be level 60 to purchase Recidivate, or have completed the first two parts to obtain part three."

Even though that can be done on the Android app (and possibly also iOS), the root cause is that the API doesn't enforce the eligibility requirements.  NOTE THOUGH: I have not confirmed that myself. If someone would like to do a test and report the results here, that would be great!

Assuming that's correct, the API should be changed to:
- make it impossible to buy a quest if you aren't eligible to do so
- make it impossible to start a quest if you aren't eligible to do so
- return an informative error message for both those cases
- have the error message documented in the API in an `@apiError` comment
- have tests for the new behaviour

**Comment by tim1234ltp** [comment]
Greetings, I would like to handle this issue.

**Comment by Alys** [comment]
@tim1234ltp Please do, thanks!

**Comment by tim1234ltp** [comment]
I have been trying to recreate such bug in my local habitRPG (web version) but still not able to purchase any quest without fulfilling eligibility requirements. Messages pop up telling me I am not meeting a particular requirement.

I am looking at habitica/website/server/controllers/api-v3/shops.js for some clues. Yet, I am still quite confused about how the purchasing is handled. Are there any other .js files I should be looking through?

**Comment by Alys** [comment]
The bug is in the API (the back-end code that implements the features that the website, mobile apps, and third-party tools use). It doesn't happen on the website because the website has its own client-side code to enforce the restrictions, but code needs to be in the API too so that you can't bypass the restrictions by using the mobile apps or any third-party tools.

These are the API routes:
https://habitica.com/apidoc/#api-User-UserPurchase
https://habitica.com/apidoc/#api-Quest-InviteToQuest

See http://habitica.wikia.com/wiki/Application_Programming_Interface for how to use command-line tools to test API routes.

To find the relevant code in the your local install, try doing `git grep` for terms or phrases that you see in those sections of the API documentation.

**Comment by tim1234ltp** [comment]
Thank you for your reply!
I followed instructions and run this:
`curl -X POST -d "type=quests&key=dilatoryDistress3" -H "x-api-user: my own user id" -H "x-api-key: my own API key" https://habitica.com/api/v3/user/purchase/quests/dilatoryDistress3`

I try to purchase the stage 3 quest that I should not be able to buy and some main problematic output is:

{**# "success":true,"**data":{"items":{"gear":{"owned":{ IGNOREING WHAT I HAVE},"quests":{**# "dilatoryDistress3":4**,"moon1":1,"dustbunnies":1,"moonstone3":1,"moonstone2":1,"goldenknight3":1,"basilist":4,"moonstone1":1,"goldenknight2":1,"goldenknight1":1,"dilatoryDistress1":0,"vice3":1,"vice2":2,"vice1":0,"atom3":1,"atom1":0,"atom2":1,"egg":1},"lastDrop":{"date":"2017-03-05T13:36:09.263Z","count":0},"currentMount":"MagicalBee-Base","currentPet":"Snake-Base"},"balance":0.5},"notifications":[]}
//I run the code few times, making it 4 scrolls for me.

The bug is recreated. Could you please advice what to do next? Where I can debug the api? What codes do I need to read and pay attention at?

ps: I used my real account and do the api thing on the real Habitica sites. I used some gems and cheated the scrolls. How to fix it? Am I actually able to do the api thing in my local Habitica?

**Comment by lulock** [comment]
Hey @tim1234ltp,

you can recreate the bug locally by using your localhost url instead of https://habitica.com/api/v3/

i.e. http://localhost:3000/api/v3/user/purchase/quests/dilatoryDistress3, or whatever port your local instance is running on. You will have to create a local user and use the local api-key to test as well. 

From there you can `git grep` any relevant terms to find code worth looking at to debug, as @Alys has suggested above. 

Hope this helps!

**Comment by Alys** [comment]
@tim1234ltp Can you tell me your User ID? I'll look into reversing the purchases you made as tests.

**Comment by tim1234ltp** [comment]
@Alys  a547cd88-24e5-46d0-bd1b-eb453f653ffe
Sorry for inconvenience! 
@lulock Thank you so much for the info!

**Comment by Alys** [comment]
@tim1234ltp I'm sorry about the delay on this. I've removed the four dilatoryDistress3 quest scrolls that you bought and given you back the 16 gems.

**Comment by tim1234ltp** [comment]
@Alys No problem! I am sorry about the progress too. I am having some serious trachea issues right now. Need a bit of time to recover.

**Comment by Alys** [comment]
@tim1234ltp That's fine! Your health is more important. This isn't a high priority issue so take your time. I hope you're feeling better soon!

**Comment by tim1234ltp** [comment]
@Alys Thanks man!
Just recovered and has a bit more investigation into the code.

I am still finding if there are any files that stored users' quest progress (ie. what quests have been unlocked) and the file that stored requirement for every quest in the Habitica. Could anyone give me some hints on this?

I figure out that 
test/common/ops/buyQuest.js
website/common/script/ops/buyQuest.js
seems to be lacking an error for not fulfilling quests requirement. These seem to be files I will be editing.

**Comment by Alys** [comment]
@tim1234ltp Habitica uses your quest achievements to work out if you've done the previous quest in a series. For example, if my quest achievements look like this:
```
"achievements.quests": {
	"whale": 7,
	"kraken": 7,
	"sheep": 8,
	"dilatoryDistress1": 1,
}
```
then I am allowed to buy `dilatoryDistress2` but not `dilatoryDistress3`.

To find the file that stores the requirements for each quest, and other data about them, do `git grep dilatoryDistress1` (or pick any other quest ID). You'll see quite a few files but this one is the one you want:
```
website/common/script/content/index.js:1835:  dilatoryDistress1: {
website/common/script/content/index.js:1868:    previous: 'dilatoryDistress1',
```
The `website/common/script/content/...` files contain details of all kinds of content. For quests, the `previous` attribute defines which quest you have to complete before you can buy it:
```
  dilatoryDistress2: {
    text: t('questDilatoryDistress2Text'),
    notes: t('questDilatoryDistress2Notes'),
    completion: t('questDilatoryDistress2Completion'),
    previous: 'dilatoryDistress1',
```

**Comment by librarianmage** [comment]
@tim1234ltp Are you still working on this?

**Comment by tim1234ltp** [comment]
@MathWhiz I am afraid not. I haven't been able to solve the issue. You can take on this though but I am not sure if there is any change to new Habitica in terms of api.

**Comment by Alys** [comment]
@tim1234ltp No worries, thanks for letting us know!

The API wasn't changed in any way that would affect this issue.

**Comment by Alys** [comment]
labels updated

**Comment by Alys** [comment]
I've removed some of the old comments from March that didn't have technical information in them to make it easier for us to focus on the tech details.

**Comment by fentie** [comment]
I can take this

**Comment by fentie** [comment]
whoops that's only changing purchase behavior, not start behavior. I'll add that part too...

**Comment by Alys** [comment]
@fentie Thanks! :)

I've updated the labels.

**Comment by fentie** [comment]
ok so as soon as this build finishes I think we're in business & ready for review. I'm having some issues locally but this _should_ fix it (with tests).
