### ISSUE TITLE
Double scrollbar when using modals

### ISSUE THREAD

**Issue by lex111** [HabitRPG/habitica#9863]
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
Browser: Google Chrome 63.0.3239.132
OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When you open any modal window, a second vertical scroll appears. It seems to me to remove the scrolling of the page and leave only the scrolling of the modal window.

![image](https://user-images.githubusercontent.com/4408379/35262792-2f9c488a-0027-11e8-9029-287e2fd8e65e.png)

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

**Comment by TheHollidayInn** [comment]
This is because we ran into issues with our modals not removing the from the body tag and preventing the body from scrolling. We've updated the libraries since then, so we could check again. Although I haven't seen complaints about the current behavior.

**Comment by mandyzhou** [comment]
I've actually been meaning to post about this for a while but never got around to it. I think this bug is more problematic than it might appear to be at first glance because once you reach the bottom (or top) of a modal, the page scroll takes over. When I try to scroll to the bottom of a modal (e.g., to allocate my attribute points), I often unintentionally start scrolling the page behind it. This kind of defeats the purpose of a modal, which is that when you're at a particular place on a page, you can open up a modal and expect to be at exactly the same spot on the original page when you close the modal.

**Comment by TheHollidayInn** [comment]
Ah, very good point. We should definitely try to remove this work around then. 

The issue is here: https://github.com/HabitRPG/habitica/blob/develop/website/client/app.vue#L94. There is also a note about what I described above (modals being dismissed without allowing the body to scroll). 

Hopefully this is fixed by upgrading to bootstrap, but I think the issue is also related to https://github.com/HabitRPG/habitica/pull/9545#issuecomment-355349414 where we have some modals dismissed incorrectly.

**Comment by lex111** [comment]
I fixed it, look please #9875

**Comment by lemoness** [comment]
Can this ticket be closed?

**Comment by paglias** [comment]
Going to close this as it seems it's been resolved

**Comment by mandyzhou** [comment]
I'm still experiencing this issue -- will the fix be live soon?

**Comment by Alys** [comment]
I've reopened this because from what I can tell we didn't push a specific fix, we just thought it had been fixed incidentally by something else. We might want to look at the linked PR to see if it's still useful.

**Comment by yb50110** [comment]
I'm not sure if this is a dumb answer, but removing the `!important` app.vue ln 111 seems to remove the extra scrollbar as well as allowing the stack on modal windows to properly show (ie. open party member and try to send message; clicking away from modal should show the party member's modal again).

 #9875 PR does indeed remove the extra scrollbar but it messes up the stack of the modal windows. So if I click on a party member, click to send a message, click away from the message modal, then I am back to the main screen (when I should be seeing the party member's modal screen again).

**Comment by TheHollidayInn** [comment]
I think you are right about the fix. It is a simple one. The issue is this: https://github.com/HabitRPG/habitica/issues/9863#issuecomment-359821737. 

We have the !important mark to prevent the bootstrap class from messing up. We've updated bootstrap vue since then, so we just need to ensure we don't revert back to scrolling issues.
